# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.37 ^0
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^-0.43 ^0
execute if entity @s[scores={AsaMatrix=11..18}] run tp @s ^0 ^-0.006249998 ^0
execute if entity @s[scores={AsaMatrix=19..21}] run tp @s ^0 ^1.145833 ^0
execute if entity @s[scores={AsaMatrix=22..25}] run tp @s ^0 ^1.359375 ^0
execute if entity @s[scores={AsaMatrix=26..28}] run tp @s ^0 ^-1.854167 ^-0.1666667
execute if entity @s[scores={AsaMatrix=29..32}] run tp @s ^0 ^-0.915625 ^-0.125
execute if entity @s[scores={AsaMatrix=33..38}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=39..58}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=59..68}] run tp @s ^0 ^0.05 ^0.1
execute if entity @s[scores={AsaMatrix=69..78}] run tp @s ^0 ^0.02 ^0.05

# 移動
    execute if entity @s[scores={AsaMatrix=1}] run summon marker ~ ~ ~ {Tags:["ZinogreMoveRotate"]}
    execute if entity @s[scores={AsaMatrix=1..25}] facing entity @e[tag=ZinogreAttackTarget,limit=1] feet rotated ~ ~ run tp @e[type=marker,tag=ZinogreMoveRotate] ^ ^ ^-5
    execute if entity @s[scores={AsaMatrix=1..10}] at @s if entity @e[tag=ZinogreAttackTarget,distance=0..6.5] run tp @s ^ ^ ^0.5 ~ ~
    execute if entity @s[scores={AsaMatrix=1..28}] at @s run function asa_animator:zinogre/anim/tail_forward/events/rotate
    execute if entity @s[scores={AsaMatrix=19..24}] at @s unless entity @e[tag=ZinogreAttackTarget,distance=0..7.5] run tp @s ^ ^ ^-0.3 ~ ~
    execute if entity @s[scores={AsaMatrix=25}] at @s run function asa_animator:zinogre/anim/tail_forward/events/pos/set_pos
    execute if entity @s[scores={AsaMatrix=26..32}] run function asa_animator:zinogre/anim/tail_forward/events/pos/offset

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/manager/5_extra/step
    execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:zinogre/manager/5_extra/step
    execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:zinogre/manager/5_extra/step
    execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:zinogre/manager/5_extra/step
    execute if entity @s[scores={AsaMatrix=18..32}] at @e[type=armor_stand,tag=ZinogreParts,tag=Tail3] run function asa_animator:zinogre/anim/sault_l/events/particle
    execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:zinogre/manager/5_extra/step

# 攻撃
    execute if entity @s[scores={AsaMatrix=33}] positioned ^ ^2 ^ run function asa_animator:zinogre/anim/tail_forward/events/damage

# 状態更新
    execute if entity @s[scores={AsaMatrix=18}] run tag @s add IsFlying
    execute if entity @s[scores={AsaMatrix=32}] run tag @s remove IsFlying

# 高度調整
    execute if entity @s[scores={AsaMatrix=11..18}] if block ~ ~0.1 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=11..18}] unless block ~ ~0.3 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~
    execute if entity @s[scores={AsaMatrix=32..48}] if block ~ ~0.5 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=32..48}] unless block ~ ~0.7 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~
    execute if entity @s[scores={AsaMatrix=58..}] if block ~ ~0.2 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=58..}] unless block ~ ~ ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~

# コンボ移行（サマーソルト）
    # execute if entity @s[tag=IsThunder,scores={AsaMatrix=38}] if predicate asa_animator:zinogre/combo run function asa_animator:zinogre/anim/tail_forward/events/change

# Keyframe Functions
function asa_animator:zinogre/get_data
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/tail_forward/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:zinogre/anim/tail_forward/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:zinogre/anim/tail_forward/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:zinogre/anim/tail_forward/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:zinogre/anim/tail_forward/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:zinogre/anim/tail_forward/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:zinogre/anim/tail_forward/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:zinogre/anim/tail_forward/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:zinogre/anim/tail_forward/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:zinogre/anim/tail_forward/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:zinogre/anim/tail_forward/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:zinogre/anim/tail_forward/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:zinogre/anim/tail_forward/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:zinogre/anim/tail_forward/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:zinogre/anim/tail_forward/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:zinogre/anim/tail_forward/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:zinogre/anim/tail_forward/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:zinogre/anim/tail_forward/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:zinogre/anim/tail_forward/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:zinogre/anim/tail_forward/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:zinogre/anim/tail_forward/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:zinogre/anim/tail_forward/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:zinogre/anim/tail_forward/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:zinogre/anim/tail_forward/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:zinogre/anim/tail_forward/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:zinogre/anim/tail_forward/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:zinogre/anim/tail_forward/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:zinogre/anim/tail_forward/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:zinogre/anim/tail_forward/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:zinogre/anim/tail_forward/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:zinogre/anim/tail_forward/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:zinogre/anim/tail_forward/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:zinogre/anim/tail_forward/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:zinogre/anim/tail_forward/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:zinogre/anim/tail_forward/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:zinogre/anim/tail_forward/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:zinogre/anim/tail_forward/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:zinogre/anim/tail_forward/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:zinogre/anim/tail_forward/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:zinogre/anim/tail_forward/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:zinogre/anim/tail_forward/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:zinogre/anim/tail_forward/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:zinogre/anim/tail_forward/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:zinogre/anim/tail_forward/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:zinogre/anim/tail_forward/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:zinogre/anim/tail_forward/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:zinogre/anim/tail_forward/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:zinogre/anim/tail_forward/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:zinogre/anim/tail_forward/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:zinogre/anim/tail_forward/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:zinogre/anim/tail_forward/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:zinogre/anim/tail_forward/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:zinogre/anim/tail_forward/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:zinogre/anim/tail_forward/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:zinogre/anim/tail_forward/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:zinogre/anim/tail_forward/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:zinogre/anim/tail_forward/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:zinogre/anim/tail_forward/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:zinogre/anim/tail_forward/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:zinogre/anim/tail_forward/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:zinogre/anim/tail_forward/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:zinogre/anim/tail_forward/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:zinogre/anim/tail_forward/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:zinogre/anim/tail_forward/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:zinogre/anim/tail_forward/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:zinogre/anim/tail_forward/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:zinogre/anim/tail_forward/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:zinogre/anim/tail_forward/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:zinogre/anim/tail_forward/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:zinogre/anim/tail_forward/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:zinogre/anim/tail_forward/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:zinogre/anim/tail_forward/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:zinogre/anim/tail_forward/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:zinogre/anim/tail_forward/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:zinogre/anim/tail_forward/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:zinogre/anim/tail_forward/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:zinogre/anim/tail_forward/keyframes/77
execute if entity @s[scores={AsaMatrix=78..}] run function asa_animator:zinogre/anim/tail_forward/keyframes/78
function asa_animator:zinogre/model
execute if entity @s[scores={AsaMatrix=79..}] run function asa_animator:zinogre/anim/tail_forward/end
