# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0.00 ^0.00 ^-0.04
execute if entity @s[scores={AsaMatrix=6..9}] run tp @s ^0.00 ^0.04 ^0.03
execute if entity @s[scores={AsaMatrix=10..15}] run tp @s ^0.00 ^0.01 ^0.02
execute if entity @s[scores={AsaMatrix=16..25}] run tp @s ^0.00 ^0.01 ^0.00
execute if entity @s[scores={AsaMatrix=26..35}] run tp @s ^0.00 ^0.01 ^0.00
execute if entity @s[scores={AsaMatrix=36..38}] run tp @s ^0.00 ^0.03 ^0.00
execute if entity @s[scores={AsaMatrix=39..40}] run tp @s ^0.00 ^-0.05 ^0.00
execute if entity @s[scores={AsaMatrix=41..42}] run tp @s ^0.00 ^-0.50 ^0.00
execute if entity @s[scores={AsaMatrix=43..44}] run tp @s ^0.00 ^0.55 ^0.03
execute if entity @s[scores={AsaMatrix=45..47}] run tp @s ^0.00 ^-0.30 ^0.02
execute if entity @s[scores={AsaMatrix=48..56}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=57..68}] run tp @s ^0.00 ^0.01 ^-0.01
execute if entity @s[scores={AsaMatrix=69..76}] run tp @s ^0.00 ^0.04 ^-0.06
execute if entity @s[scores={AsaMatrix=77..82}] run tp @s ^0.00 ^0.01 ^-0.03
execute if entity @s[scores={AsaMatrix=83..86}] run tp @s ^0.00 ^0.01 ^-0.02
execute if entity @s[scores={AsaMatrix=87..90}] run tp @s ^0.00 ^0.00 ^-0.05

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/manager/5_extra/step
    execute if entity @s[scores={AsaMatrix=15}] run summon lightning_bolt ~ 255 ~
    execute if entity @s[scores={AsaMatrix=6..42}] at @s run function asa_animator:zinogre/anim/chargehand_r/events/particle

# 移動
    execute if entity @s[scores={AsaMatrix=1..32}] run function asa_animator:zinogre/manager/4_general/rotate_fast
    execute if entity @s[scores={AsaMatrix=33}] at @s run function asa_animator:zinogre/anim/chargehand_l/events/pos/set_pos
    execute if entity @s[scores={AsaMatrix=35..42}] run function asa_animator:zinogre/anim/chargehand_l/events/pos/offset

# 攻撃
    execute if entity @s[scores={AsaMatrix=42}] positioned ^-2 ^ ^7 run function asa_animator:zinogre/anim/chargehand_l/events/damage_h
    execute if entity @s[scores={AsaMatrix=52}] positioned ^-5 ^ ^12 run function asa_animator:zinogre/anim/chargehand_l/events/damage_t
    execute if entity @s[scores={AsaMatrix=52}] positioned ^1 ^ ^12 run function asa_animator:zinogre/anim/chargehand_l/events/damage_t
    execute if entity @s[scores={AsaMatrix=57}] positioned ^-4 ^ ^18.5 run function asa_animator:zinogre/anim/chargehand_l/events/damage_t
    execute if entity @s[scores={AsaMatrix=57}] positioned ^0 ^ ^18.5 run function asa_animator:zinogre/anim/chargehand_l/events/damage_t
    execute if entity @s[scores={AsaMatrix=57}] positioned ^-8 ^ ^17 run function asa_animator:zinogre/anim/chargehand_l/events/damage_t
    execute if entity @s[scores={AsaMatrix=57}] positioned ^4 ^ ^17 run function asa_animator:zinogre/anim/chargehand_l/events/damage_t

# 高度調整
    execute if entity @s[scores={AsaMatrix=1..32}] at @s if block ~ ~-0.1 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=1..32}] at @s unless block ~ ~0.1 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=69..}] at @s if block ~ ~-0.1 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=69..}] at @s unless block ~ ~0.1 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~ ~ ~

# 移行
    # execute if entity @s[tag=IsAnger,tag=!IsHandC2,scores={AsaMatrix=45}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/events/change

# Keyframe Functions
function asa_animator:zinogre/get_data
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/77
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/78
execute if entity @s[scores={AsaMatrix=79}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/79
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/80
execute if entity @s[scores={AsaMatrix=81}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/81
execute if entity @s[scores={AsaMatrix=82}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/82
execute if entity @s[scores={AsaMatrix=83}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/83
execute if entity @s[scores={AsaMatrix=84}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/84
execute if entity @s[scores={AsaMatrix=85}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/85
execute if entity @s[scores={AsaMatrix=86}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/86
execute if entity @s[scores={AsaMatrix=87}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/87
execute if entity @s[scores={AsaMatrix=88}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/88
execute if entity @s[scores={AsaMatrix=89}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/89
execute if entity @s[scores={AsaMatrix=90..}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/keyframes/90
function asa_animator:zinogre/model
execute if entity @s[scores={AsaMatrix=91..}] run function asa_animator:zinogre/anim/hand_l_to_chargehand_r/end
