# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/dash_start/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/dash_start/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/dash_start/keyframes/1
execute if entity @s[scores={AsaMatrix=8..12}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=13..}] run function asa_animator:reus/anim/dash_start/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=1..3}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
