# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0.2125 ^-0.0375
execute if entity @s[scores={AsaMatrix=9..16}] run tp @s ^0 ^-0.0625 ^0 ~3 ~
execute if entity @s[scores={AsaMatrix=17..25}] run tp @s ^0 ^-0.05555556 ^0
execute if entity @s[scores={AsaMatrix=26..29}] run tp @s ^0 ^0 ^0 ~-12 ~
execute if entity @s[scores={AsaMatrix=30..33}] run tp @s ^0 ^0 ^0 ~-12 ~
execute if entity @s[scores={AsaMatrix=34..41}] run tp @s ^0 ^0.25 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=42..50}] run tp @s ^0 ^-0.2666667 ^0.02222222 ~9 ~
execute if entity @s[scores={AsaMatrix=51..56}] run tp @s ^0 ^0.04166667 ^0 ~1 ~
execute if entity @s[scores={AsaMatrix=57..67}] run tp @s ^0 ^0.00227273 ^0
execute if entity @s[scores={AsaMatrix=68..78}] run tp @s ^0 ^0.00227273 ^0
execute if entity @s[scores={AsaMatrix=79..90}] run tp @s ^0 ^0.06666666 ^0.008333334
execute if entity @s[scores={AsaMatrix=91..105}] run tp @s ^0 ^-0.09333333 ^0

# 移動
    execute if entity @s[scores={AsaMatrix=1..13}] unless entity @e[tag=ReusAttackTarget,distance=..6] at @s run tp @s ^ ^ ^0.2
    execute if entity @s[scores={AsaMatrix=1..13}] run function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=8}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=24}] run playsound entity.player.attack.sweep master @a ~ ~ ~ 2 0.5
    execute if entity @s[scores={AsaMatrix=26}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=41}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=90}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=47..67}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 1 0.82 1

# 攻撃
    execute if entity @s[scores={AsaMatrix=26..33}] rotated ~3 ~ run function asa_animator:reus/anim/flying_tail/events/damage

# 高度調整
    execute if entity @s[scores={AsaMatrix=9..24}] at @s if block ~ ~-1.2 ~ #asa_animator:no_collision at @s run tp @s ~ ~-0.2 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=9..24}] at @s unless block ~ ~-0.5 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.2 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=42..73}] at @s if block ~ ~-1.7 ~ #asa_animator:no_collision at @s run tp @s ~ ~-0.2 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=42..73}] at @s unless block ~ ~-1.0 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.2 ~ ~ ~

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/flying_tail/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/flying_tail/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/flying_tail/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/flying_tail/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/flying_tail/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_tail/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/flying_tail/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_tail/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_tail/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/flying_tail/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_tail/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/flying_tail/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/flying_tail/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/flying_tail/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/flying_tail/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/flying_tail/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_tail/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/flying_tail/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/flying_tail/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/flying_tail/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/flying_tail/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/flying_tail/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/flying_tail/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/flying_tail/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/flying_tail/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/flying_tail/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/flying_tail/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/flying_tail/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/flying_tail/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/flying_tail/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/flying_tail/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/flying_tail/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/flying_tail/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/flying_tail/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/flying_tail/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/flying_tail/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/flying_tail/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/flying_tail/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/flying_tail/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/flying_tail/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/flying_tail/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/flying_tail/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/flying_tail/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/flying_tail/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/flying_tail/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/flying_tail/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/flying_tail/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/flying_tail/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/flying_tail/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/flying_tail/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/flying_tail/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/flying_tail/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/flying_tail/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/flying_tail/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/flying_tail/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/flying_tail/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/flying_tail/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/flying_tail/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/flying_tail/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/flying_tail/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/flying_tail/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/flying_tail/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/flying_tail/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/flying_tail/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/flying_tail/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/flying_tail/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/flying_tail/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/flying_tail/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/flying_tail/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:reus/anim/flying_tail/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/flying_tail/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:reus/anim/flying_tail/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:reus/anim/flying_tail/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:reus/anim/flying_tail/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:reus/anim/flying_tail/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/flying_tail/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:reus/anim/flying_tail/keyframes/77
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:reus/anim/flying_tail/keyframes/78
execute if entity @s[scores={AsaMatrix=79}] run function asa_animator:reus/anim/flying_tail/keyframes/79
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:reus/anim/flying_tail/keyframes/80
execute if entity @s[scores={AsaMatrix=81}] run function asa_animator:reus/anim/flying_tail/keyframes/81
execute if entity @s[scores={AsaMatrix=82}] run function asa_animator:reus/anim/flying_tail/keyframes/82
execute if entity @s[scores={AsaMatrix=83}] run function asa_animator:reus/anim/flying_tail/keyframes/83
execute if entity @s[scores={AsaMatrix=84}] run function asa_animator:reus/anim/flying_tail/keyframes/84
execute if entity @s[scores={AsaMatrix=85}] run function asa_animator:reus/anim/flying_tail/keyframes/85
execute if entity @s[scores={AsaMatrix=86}] run function asa_animator:reus/anim/flying_tail/keyframes/86
execute if entity @s[scores={AsaMatrix=87}] run function asa_animator:reus/anim/flying_tail/keyframes/87
execute if entity @s[scores={AsaMatrix=88}] run function asa_animator:reus/anim/flying_tail/keyframes/88
execute if entity @s[scores={AsaMatrix=89}] run function asa_animator:reus/anim/flying_tail/keyframes/89
execute if entity @s[scores={AsaMatrix=90}] run function asa_animator:reus/anim/flying_tail/keyframes/90
execute if entity @s[scores={AsaMatrix=91}] run function asa_animator:reus/anim/flying_tail/keyframes/91
execute if entity @s[scores={AsaMatrix=92}] run function asa_animator:reus/anim/flying_tail/keyframes/92
execute if entity @s[scores={AsaMatrix=93}] run function asa_animator:reus/anim/flying_tail/keyframes/93
execute if entity @s[scores={AsaMatrix=94}] run function asa_animator:reus/anim/flying_tail/keyframes/94
execute if entity @s[scores={AsaMatrix=95}] run function asa_animator:reus/anim/flying_tail/keyframes/95
execute if entity @s[scores={AsaMatrix=96}] run function asa_animator:reus/anim/flying_tail/keyframes/96
execute if entity @s[scores={AsaMatrix=97}] run function asa_animator:reus/anim/flying_tail/keyframes/97
execute if entity @s[scores={AsaMatrix=98}] run function asa_animator:reus/anim/flying_tail/keyframes/98
execute if entity @s[scores={AsaMatrix=99}] run function asa_animator:reus/anim/flying_tail/keyframes/99
execute if entity @s[scores={AsaMatrix=100}] run function asa_animator:reus/anim/flying_tail/keyframes/100
execute if entity @s[scores={AsaMatrix=101}] run function asa_animator:reus/anim/flying_tail/keyframes/101
execute if entity @s[scores={AsaMatrix=102}] run function asa_animator:reus/anim/flying_tail/keyframes/102
execute if entity @s[scores={AsaMatrix=103}] run function asa_animator:reus/anim/flying_tail/keyframes/103
execute if entity @s[scores={AsaMatrix=104}] run function asa_animator:reus/anim/flying_tail/keyframes/104
execute if entity @s[scores={AsaMatrix=105..}] run function asa_animator:reus/anim/flying_tail/keyframes/105
execute if entity @s[scores={AsaMatrix=106..}] run function asa_animator:reus/anim/flying_tail/end
function asa_animator:reus/model
