# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0.00 ^-0.01 ^0.00
execute if entity @s[scores={AsaMatrix=8..14}] run tp @s ^0.00 ^0.03 ^0.00
execute if entity @s[scores={AsaMatrix=15..34}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=35..40}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=41..46}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=47..52}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=53..62}] run tp @s ^0.00 ^-0.01 ^0.00
execute if entity @s[scores={AsaMatrix=63..75}] run tp @s ^0.00 ^0.01 ^0.00

# 演出
    execute if entity @s[scores={AsaMatrix=14..20}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 1 0.82 1

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/after_attack/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/after_attack/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/after_attack/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/after_attack/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/after_attack/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/after_attack/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/after_attack/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/after_attack/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/after_attack/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/after_attack/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/after_attack/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/after_attack/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/after_attack/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/after_attack/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/after_attack/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/after_attack/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/after_attack/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/after_attack/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/after_attack/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/after_attack/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/after_attack/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/after_attack/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/after_attack/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/after_attack/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/after_attack/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/after_attack/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/after_attack/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/after_attack/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/after_attack/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/after_attack/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/after_attack/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/after_attack/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/after_attack/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/after_attack/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/after_attack/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/after_attack/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/after_attack/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/after_attack/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/after_attack/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/after_attack/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/after_attack/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/after_attack/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/after_attack/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/after_attack/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/after_attack/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/after_attack/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/after_attack/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/after_attack/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/after_attack/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/after_attack/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/after_attack/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/after_attack/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/after_attack/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/after_attack/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/after_attack/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/after_attack/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/after_attack/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/after_attack/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/after_attack/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/after_attack/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/after_attack/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/after_attack/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/after_attack/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/after_attack/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/after_attack/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/after_attack/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/after_attack/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/after_attack/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/after_attack/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:reus/anim/after_attack/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/after_attack/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:reus/anim/after_attack/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:reus/anim/after_attack/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:reus/anim/after_attack/keyframes/74
execute if entity @s[scores={AsaMatrix=75..}] run function asa_animator:reus/anim/after_attack/keyframes/75
execute if entity @s[scores={AsaMatrix=76..}] run function asa_animator:reus/anim/after_attack/end
function asa_animator:reus/model
