# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/after_attack/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/after_attack/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^-0.01428571 ^0
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/after_attack/keyframes/1
execute if entity @s[scores={AsaMatrix=8..14}] run tp @s ^0 ^0.02857143 ^0
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/after_attack/keyframes/2
execute if entity @s[scores={AsaMatrix=15..49}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/after_attack/keyframes/3
execute if entity @s[scores={AsaMatrix=50..55}] run tp @s ^0 ^-0.004166666 ^0
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/after_attack/keyframes/4
execute if entity @s[scores={AsaMatrix=56..61}] run tp @s ^0 ^-0.004166667 ^0
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/after_attack/keyframes/5
execute if entity @s[scores={AsaMatrix=62..67}] run tp @s ^0 ^-0.004166667 ^0
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/after_attack/keyframes/6
execute if entity @s[scores={AsaMatrix=68..77}] run tp @s ^0 ^-0.0125 ^0
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:reus/anim/after_attack/keyframes/7
execute if entity @s[scores={AsaMatrix=78..90}] run tp @s ^0 ^0.007692308 ^0
execute if entity @s[scores={AsaMatrix=91..}] run function asa_animator:reus/anim/after_attack/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 演出
    execute if entity @s[scores={AsaMatrix=14..20}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 1 0.82 1