# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^-0.0625 ^0
execute if entity @s[scores={AsaMatrix=9..13}] run tp @s ^0 ^0.2 ^0
execute if entity @s[scores={AsaMatrix=14..18}] run tp @s ^-0.5 ^0.18 ^0
execute if entity @s[scores={AsaMatrix=19..23}] run tp @s ^-0.2 ^-0.34 ^0
execute if entity @s[scores={AsaMatrix=24..33}] run tp @s ^-0.2 ^0.02999999 ^0.2

# 移動
    function asa_animator:reus/manager/4_general/rotate_fast
    execute if entity @s[scores={AsaMatrix=1}] facing entity @e[tag=ReusAttackTarget,limit=1] feet rotated ~ 0 run function asa_animator:reus/anim/flying_move_land_r/events/pos/set_pos_0
    execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_move_land_r/events/pos/set_pos_1
    execute if entity @s[scores={AsaMatrix=1..14}] at @s run function asa_animator:reus/anim/flying_move_land_r/events/pos/offset

# 演出
    execute if entity @s[scores={AsaMatrix=6}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=22}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=22..}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/manager/5_extra/change_to_normal

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/32
execute if entity @s[scores={AsaMatrix=33..}] run function asa_animator:reus/anim/flying_move_land_r/keyframes/33
execute if entity @s[scores={AsaMatrix=34..}] run function asa_animator:reus/anim/flying_move_land_r/end
function asa_animator:reus/model
