# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/turn_l/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/turn_l/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.02 ^0
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/turn_l/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^-0.04 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/turn_l/keyframes/2
execute if entity @s[scores={AsaMatrix=11..15}] run tp @s ^0 ^0.04 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/turn_l/keyframes/3
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^0 ^-0.04 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/turn_l/keyframes/4
execute if entity @s[scores={AsaMatrix=21..26}] run tp @s ^0 ^0.01666667 ^0
execute if entity @s[scores={AsaMatrix=27..}] run function asa_animator:reus/anim/turn_l/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 移動
    function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=10}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=20}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7