# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_turn/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_turn/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^-0.11 ^0
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_turn/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^0.29 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_turn/keyframes/2
execute if entity @s[scores={AsaMatrix=11..20}] run tp @s ^0 ^-0.09 ^-0.02
execute if entity @s[scores={AsaMatrix=21..}] run function asa_animator:reus/anim/flying_turn/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 移動
    function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=8}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

# 高度調整
    execute at @s if block ~ ~-3 ~ #asa_animator:no_collision at @s run tp @s ~ ~-0.5 ~ ~ ~
    execute at @s unless block ~ ~-2 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.5 ~ ~ ~