# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0.3 ^0.03333334
execute if entity @s[scores={AsaMatrix=7..12}] run tp @s ^0 ^0.1333333 ^-0.01666667
execute if entity @s[scores={AsaMatrix=13..18}] run tp @s ^0 ^0.1333333 ^-0.01666667
execute if entity @s[scores={AsaMatrix=19..24}] run tp @s ^0 ^0.2333333 ^-0.05
execute if entity @s[scores={AsaMatrix=25..30}] run tp @s ^0 ^-0.06666669 ^0.05
execute if entity @s[scores={AsaMatrix=31..35}] run tp @s ^0 ^-0.1 ^0
execute if entity @s[scores={AsaMatrix=36..40}] run tp @s ^0 ^0.1 ^0
execute if entity @s[scores={AsaMatrix=41..46}] run tp @s ^0 ^0.06666669 ^-0.03333334 ~0.5 ~
execute if entity @s[scores={AsaMatrix=47..55}] run tp @s ^0 ^0.0111111 ^-0.04444445
execute if entity @s[scores={AsaMatrix=56..67}] run tp @s ^0 ^-0.25 ^-0.01666667
execute if entity @s[scores={AsaMatrix=68..79}] run tp @s ^0 ^-0.075 ^0.03333334

# 移動
    execute if entity @s[scores={AsaMatrix=1..10}] run function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=1..29}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..12] at @s positioned ^ ^1.3 ^0.8 run particle flame ~ ~ ~ 0.2 0.2 0.2 0.1 3
    execute if entity @s[scores={AsaMatrix=1}] run playsound entity.player.breath master @a ~ ~ ~ 2 0.8
    execute if entity @s[scores={AsaMatrix=6}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=18}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=30}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=67}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

# 攻撃
    # 位置決定
        execute if entity @s[scores={AsaMatrix=26}] run summon marker ^ ^-4 ^6 {Tags:["ReusBreathTarget"]}
        execute if entity @s[scores={AsaMatrix=26}] if entity @e[tag=ReusAttackTarget,distance=5..30] at @e[tag=ReusAttackTarget,limit=1] run tp @e[type=marker,tag=ReusBreathTarget] ~ ~ ~
    # 角度決定
        execute if entity @s[scores={AsaMatrix=30}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..7] at @s run function asa_animator:reus/anim/flying_breath_large/events/attack_start
    # 攻撃
        execute if entity @s[scores={AsaMatrix=30..39}] as @e[type=marker,tag=ReusChargeFPos,distance=0..7] at @s run function asa_animator:reus/anim/flying_breath_large/events/attack
    # 終了
        execute if entity @s[scores={AsaMatrix=40}] run kill @e[type=marker,tag=ReusChargeFPos]

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/flying_breath_large/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/flying_breath_large/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/flying_breath_large/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/flying_breath_large/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/flying_breath_large/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_breath_large/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/flying_breath_large/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_breath_large/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_breath_large/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/flying_breath_large/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_breath_large/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/flying_breath_large/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/flying_breath_large/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/flying_breath_large/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/flying_breath_large/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/flying_breath_large/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_breath_large/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/flying_breath_large/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/flying_breath_large/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/flying_breath_large/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/flying_breath_large/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/flying_breath_large/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/flying_breath_large/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/flying_breath_large/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/flying_breath_large/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/flying_breath_large/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/flying_breath_large/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/flying_breath_large/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/flying_breath_large/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/flying_breath_large/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/flying_breath_large/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/flying_breath_large/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/flying_breath_large/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/flying_breath_large/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/flying_breath_large/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/flying_breath_large/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/flying_breath_large/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/flying_breath_large/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/flying_breath_large/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/flying_breath_large/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/flying_breath_large/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/flying_breath_large/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/flying_breath_large/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/flying_breath_large/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/flying_breath_large/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/flying_breath_large/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/flying_breath_large/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/flying_breath_large/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/flying_breath_large/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/flying_breath_large/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/flying_breath_large/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/flying_breath_large/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/flying_breath_large/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/flying_breath_large/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/flying_breath_large/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/flying_breath_large/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/flying_breath_large/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/flying_breath_large/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/flying_breath_large/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/flying_breath_large/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/flying_breath_large/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/flying_breath_large/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/flying_breath_large/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/flying_breath_large/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/flying_breath_large/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/flying_breath_large/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/flying_breath_large/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/flying_breath_large/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/flying_breath_large/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:reus/anim/flying_breath_large/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/flying_breath_large/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:reus/anim/flying_breath_large/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:reus/anim/flying_breath_large/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:reus/anim/flying_breath_large/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:reus/anim/flying_breath_large/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/flying_breath_large/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:reus/anim/flying_breath_large/keyframes/77
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:reus/anim/flying_breath_large/keyframes/78
execute if entity @s[scores={AsaMatrix=79..}] run function asa_animator:reus/anim/flying_breath_large/keyframes/79
execute if entity @s[scores={AsaMatrix=80..}] run function asa_animator:reus/anim/flying_breath_large/end
function asa_animator:reus/model
