# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..10}] run tp @s ^0.00 ^0.00 ^0.00

# 高度調整
    execute if block ~ ~-0.2 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute unless block ~ ~ ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~

# Keyframe Functions
function asa_animator:zinogre/get_data
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/stay/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:zinogre/anim/stay/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:zinogre/anim/stay/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:zinogre/anim/stay/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:zinogre/anim/stay/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:zinogre/anim/stay/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:zinogre/anim/stay/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:zinogre/anim/stay/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:zinogre/anim/stay/keyframes/9
execute if entity @s[scores={AsaMatrix=10..}] run function asa_animator:zinogre/anim/stay/keyframes/10
function asa_animator:zinogre/model
execute if entity @s[scores={AsaMatrix=11..}] run function asa_animator:zinogre/anim/stay/end