# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0.03333334 ^-0.08333334
execute if entity @s[scores={AsaMatrix=7..12}] run tp @s ^0 ^0.04166666 ^0.3
execute if entity @s[scores={AsaMatrix=13..18}] run tp @s ^0 ^0.04166667 ^0.3
execute if entity @s[scores={AsaMatrix=19..26}] run tp @s ^0 ^-0.125 ^0.8
execute if entity @s[scores={AsaMatrix=27..30}] run tp @s ^0 ^-0.075 ^1.4
execute if entity @s[scores={AsaMatrix=31..34}] run tp @s ^0 ^-0.09999999 ^0.2
execute if entity @s[scores={AsaMatrix=35..50}] run tp @s ^0 ^0.0625 ^0.1

# 移動
    execute if entity @s[scores={AsaMatrix=1..13}] run function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=6}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=18}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=34}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[tag=IsAnger,scores={AsaMatrix=18..34}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..12] at @s positioned ^ ^1.1 ^0.5 run particle flame ~ ~ ~ 0.2 0.2 0.2 0.1 3

# 攻撃
    execute if entity @s[scores={AsaMatrix=20..34}] run function asa_animator:reus/anim/flying_bite/events/damage
    execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/bite/events/damage

# 高度調整
    execute if entity @s[scores={AsaMatrix=12..35}] at @s if block ~ ~-1.2 ~ #asa_animator:no_collision at @s run tp @s ~ ~-0.5 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=12..35}] at @s unless block ~ ~-0.5 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.5 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=40..}] at @s if block ~ ~-2 ~ #asa_animator:no_collision at @s run tp @s ~ ~-0.3 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=40..}] at @s unless block ~ ~-3 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.3 ~ ~ ~

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/flying_bite/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/flying_bite/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/flying_bite/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/flying_bite/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/flying_bite/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_bite/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/flying_bite/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_bite/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_bite/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/flying_bite/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_bite/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/flying_bite/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/flying_bite/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/flying_bite/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/flying_bite/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/flying_bite/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_bite/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/flying_bite/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/flying_bite/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/flying_bite/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/flying_bite/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/flying_bite/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/flying_bite/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/flying_bite/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/flying_bite/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/flying_bite/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/flying_bite/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/flying_bite/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/flying_bite/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/flying_bite/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/flying_bite/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/flying_bite/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/flying_bite/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/flying_bite/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/flying_bite/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/flying_bite/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/flying_bite/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/flying_bite/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/flying_bite/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/flying_bite/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/flying_bite/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/flying_bite/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/flying_bite/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/flying_bite/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/flying_bite/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/flying_bite/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/flying_bite/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/flying_bite/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/flying_bite/keyframes/49
execute if entity @s[scores={AsaMatrix=50..}] run function asa_animator:reus/anim/flying_bite/keyframes/50
execute if entity @s[scores={AsaMatrix=51..}] run function asa_animator:reus/anim/flying_bite/end
function asa_animator:reus/model
