# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0.00 ^-0.06 ^0.20 ~0.5 ~
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0.00 ^0.36 ^0.20 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=11..20}] run tp @s ^0.00 ^0.10 ^0.10 ~ ~


# 演出
    execute if entity @s[scores={AsaMatrix=5}] run particle block grass_block ~ ~0.1 ~ 1 0.1 1 0 10
    execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=10}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/manager/5_extra/change_to_fly

# 風圧
    execute if entity @s[scores={AsaMatrix=10}] as @a[distance=0..5] run function mhdp_core:player/damage/knockback/wind/1
    execute if entity @s[scores={AsaMatrix=10}] as @a[distance=5.1..8] run function mhdp_core:player/damage/knockback/wind/0

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/start_fly/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/start_fly/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/start_fly/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/start_fly/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/start_fly/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/start_fly/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/start_fly/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/start_fly/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/start_fly/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/start_fly/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/start_fly/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/start_fly/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/start_fly/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/start_fly/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/start_fly/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/start_fly/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/start_fly/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/start_fly/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/start_fly/keyframes/19
execute if entity @s[scores={AsaMatrix=20..}] run function asa_animator:reus/anim/start_fly/keyframes/20
execute if entity @s[scores={AsaMatrix=21..}] run function asa_animator:reus/anim/start_fly/end
function asa_animator:reus/model
