# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/bstep/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/bstep/keyframes/0
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0.5 ^-0.75
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/bstep/keyframes/1
execute if entity @s[scores={AsaMatrix=7..12}] run tp @s ^0 ^-0.2666667 ^-0.25
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/bstep/keyframes/2
execute if entity @s[scores={AsaMatrix=13..18}] run tp @s ^0 ^-0.275 ^-0.08333334
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/bstep/keyframes/3
execute if entity @s[scores={AsaMatrix=19..25}] run tp @s ^0 ^0.03571429 ^-0.1714285
execute if entity @s[scores={AsaMatrix=26..}] run function asa_animator:reus/anim/bstep/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 移動
    function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/manager/5_extra/change_to_fly
    execute if entity @s[scores={AsaMatrix=7}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/manager/5_extra/change_to_normal
    execute if entity @s[scores={AsaMatrix=18..20}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=18}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7

# 高度調整
    execute if entity @s[scores={AsaMatrix=19..25}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=19..25}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~
