# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^-0.0375 ^0
execute if entity @s[scores={AsaMatrix=9..15}] run tp @s ^0 ^-0.05714286 ^-0.01428571
execute if entity @s[scores={AsaMatrix=16..23}] run tp @s ^0 ^0.1 ^-0.1125
execute if entity @s[scores={AsaMatrix=24..28}] run tp @s ^0 ^0.16 ^-0.18
execute if entity @s[scores={AsaMatrix=29..35}] run tp @s ^0 ^-0.1285714 ^0.08571429
execute if entity @s[scores={AsaMatrix=36..41}] run tp @s ^0 ^0.2333333 ^-0.03333334
execute if entity @s[scores={AsaMatrix=42..48}] run tp @s ^0 ^-0.2 ^0.02857144
execute if entity @s[scores={AsaMatrix=49..54}] run tp @s ^0 ^0.2333333 ^-0.03333334
execute if entity @s[scores={AsaMatrix=55..61}] run tp @s ^0 ^-0.2 ^0.02857144
execute if entity @s[scores={AsaMatrix=62..70}] run tp @s ^0 ^0.1777778 ^-0.02222223
execute if entity @s[scores={AsaMatrix=71..78}] run tp @s ^0 ^-0.1375 ^-0.07499999
execute if entity @s[scores={AsaMatrix=79..93}] run tp @s ^0 ^-0.03333334 ^-0.08000002

# 移動
    execute if entity @s[scores={AsaMatrix=1..13}] run function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run playsound entity.player.breath master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=8}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=23}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=41}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=54}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=70}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

# 発射位置決定
    execute if entity @s[scores={AsaMatrix=13}] run summon marker ^ ^0.7 ^8 {Tags:["ReusBreathTarget"]}
    execute if entity @s[scores={AsaMatrix=13}] rotated as @s rotated ~ 0 unless entity @e[tag=ReusAttackTarget,distance=0..8] positioned as @e[tag=ReusAttackTarget,limit=1] run tp @e[type=marker,tag=ReusBreathTarget] ~ ~1 ~ ~ ~

# ブレス発射
    execute if entity @s[scores={AsaMatrix=35}] as @e[type=marker,tag=ReusBreathTarget] at @s run tp @s ^ ^ ^1
    execute if entity @s[scores={AsaMatrix=35}] positioned ^ ^4 ^4 facing entity @e[type=marker,tag=ReusBreathTarget,limit=1] feet run function asa_animator:reus/anim/flying_breath_3/events/shot
    execute if entity @s[scores={AsaMatrix=35}] as @e[type=marker,tag=ReusBreathTarget] at @s run tp @s ^-7 ^ ^-2.5
    execute if entity @s[scores={AsaMatrix=48}] positioned ^-1 ^4 ^4 facing entity @e[type=marker,tag=ReusBreathTarget,limit=1] feet run function asa_animator:reus/anim/flying_breath_3/events/shot
    execute if entity @s[scores={AsaMatrix=48}] as @e[type=marker,tag=ReusBreathTarget] at @s run tp @s ^14 ^ ^
    execute if entity @s[scores={AsaMatrix=61}] positioned ^1 ^4 ^4 facing entity @e[type=marker,tag=ReusBreathTarget,limit=1] feet run function asa_animator:reus/anim/flying_breath_3/events/shot
    execute if entity @s[scores={AsaMatrix=61}] run kill @e[tag=ReusBreathTarget]
    
# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/flying_breath_3/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/flying_breath_3/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/flying_breath_3/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/flying_breath_3/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/flying_breath_3/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_breath_3/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/flying_breath_3/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_breath_3/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_breath_3/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/flying_breath_3/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_breath_3/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/flying_breath_3/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/flying_breath_3/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/flying_breath_3/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/flying_breath_3/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/flying_breath_3/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_breath_3/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/flying_breath_3/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/flying_breath_3/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/flying_breath_3/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/flying_breath_3/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/flying_breath_3/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/flying_breath_3/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/flying_breath_3/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/flying_breath_3/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/flying_breath_3/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/flying_breath_3/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/flying_breath_3/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/flying_breath_3/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/flying_breath_3/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/flying_breath_3/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/flying_breath_3/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/flying_breath_3/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/flying_breath_3/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/flying_breath_3/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/flying_breath_3/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/flying_breath_3/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/flying_breath_3/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/flying_breath_3/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/flying_breath_3/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/flying_breath_3/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/flying_breath_3/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/flying_breath_3/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/flying_breath_3/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/flying_breath_3/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/flying_breath_3/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/flying_breath_3/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/flying_breath_3/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/flying_breath_3/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/flying_breath_3/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/flying_breath_3/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/flying_breath_3/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/flying_breath_3/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/flying_breath_3/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/flying_breath_3/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/flying_breath_3/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/flying_breath_3/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/flying_breath_3/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/flying_breath_3/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/flying_breath_3/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/flying_breath_3/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/flying_breath_3/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/flying_breath_3/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/flying_breath_3/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/flying_breath_3/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/flying_breath_3/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/flying_breath_3/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/flying_breath_3/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/flying_breath_3/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:reus/anim/flying_breath_3/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/flying_breath_3/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:reus/anim/flying_breath_3/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:reus/anim/flying_breath_3/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:reus/anim/flying_breath_3/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:reus/anim/flying_breath_3/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/flying_breath_3/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:reus/anim/flying_breath_3/keyframes/77
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:reus/anim/flying_breath_3/keyframes/78
execute if entity @s[scores={AsaMatrix=79}] run function asa_animator:reus/anim/flying_breath_3/keyframes/79
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:reus/anim/flying_breath_3/keyframes/80
execute if entity @s[scores={AsaMatrix=81}] run function asa_animator:reus/anim/flying_breath_3/keyframes/81
execute if entity @s[scores={AsaMatrix=82}] run function asa_animator:reus/anim/flying_breath_3/keyframes/82
execute if entity @s[scores={AsaMatrix=83}] run function asa_animator:reus/anim/flying_breath_3/keyframes/83
execute if entity @s[scores={AsaMatrix=84}] run function asa_animator:reus/anim/flying_breath_3/keyframes/84
execute if entity @s[scores={AsaMatrix=85}] run function asa_animator:reus/anim/flying_breath_3/keyframes/85
execute if entity @s[scores={AsaMatrix=86}] run function asa_animator:reus/anim/flying_breath_3/keyframes/86
execute if entity @s[scores={AsaMatrix=87}] run function asa_animator:reus/anim/flying_breath_3/keyframes/87
execute if entity @s[scores={AsaMatrix=88}] run function asa_animator:reus/anim/flying_breath_3/keyframes/88
execute if entity @s[scores={AsaMatrix=89}] run function asa_animator:reus/anim/flying_breath_3/keyframes/89
execute if entity @s[scores={AsaMatrix=90}] run function asa_animator:reus/anim/flying_breath_3/keyframes/90
execute if entity @s[scores={AsaMatrix=91}] run function asa_animator:reus/anim/flying_breath_3/keyframes/91
execute if entity @s[scores={AsaMatrix=92}] run function asa_animator:reus/anim/flying_breath_3/keyframes/92
execute if entity @s[scores={AsaMatrix=93..}] run function asa_animator:reus/anim/flying_breath_3/keyframes/93
execute if entity @s[scores={AsaMatrix=94..}] run function asa_animator:reus/anim/flying_breath_3/end
function asa_animator:reus/model
