# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..10}] run tp @s ^0 ^0.01 ^0
execute if entity @s[scores={AsaMatrix=11..20}] run tp @s ^0 ^-0.01 ^-0.03
execute if entity @s[scores={AsaMatrix=21..27}] run tp @s ^0 ^0.01428571 ^-0.05714285
execute if entity @s[scores={AsaMatrix=28..50}] run tp @s ^0 ^0.004347826 ^0.02608696
execute if entity @s[scores={AsaMatrix=51..60}] run tp @s ^0 ^-0.04 ^0.01
execute if entity @s[scores={AsaMatrix=61..70}] run tp @s ^0 ^0.02 ^0

# 移動
    execute if entity @s[scores={AsaMatrix=1..20}] run function asa_animator:reus/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/manager/5_extra/change_to_normal
    execute if entity @s[scores={AsaMatrix=1}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=68}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=22}] run playsound entity.ender_dragon.growl master @a[distance=..48] ~ ~ ~ 1 0.5 1
    execute if entity @s[scores={AsaMatrix=27..55}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 1 0.7 1
    execute if entity @s[scores={AsaMatrix=27..50}] at @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..20] positioned ^ ^1.1 ^0.7 run particle flash ~ ~ ~ 0 0 0 0 1
    execute if entity @s[scores={AsaMatrix=27..50}] positioned ^ ^ ^6 run particle block grass_block ~ ~ ~ 2 0.1 2 0 5

# 咆哮怯み
    execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/voice/events/damage

# 高度調整
    execute at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/voice/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/voice/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/voice/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/voice/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/voice/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/voice/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/voice/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/voice/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/voice/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/voice/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/voice/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/voice/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/voice/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/voice/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/voice/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/voice/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/voice/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/voice/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/voice/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/voice/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/voice/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/voice/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/voice/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/voice/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/voice/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/voice/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/voice/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/voice/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/voice/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/voice/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/voice/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/voice/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/voice/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/voice/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/voice/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/voice/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/voice/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/voice/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/voice/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/voice/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/voice/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/voice/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/voice/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/voice/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/voice/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/voice/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/voice/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/voice/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/voice/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/voice/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/voice/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/voice/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/voice/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/voice/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/voice/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/voice/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/voice/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/voice/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/voice/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/voice/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/voice/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/voice/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/voice/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/voice/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/voice/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/voice/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/voice/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/voice/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/voice/keyframes/69
execute if entity @s[scores={AsaMatrix=70..}] run function asa_animator:reus/anim/voice/keyframes/70
execute if entity @s[scores={AsaMatrix=71..}] run function asa_animator:reus/anim/anger/end
function asa_animator:reus/model
