# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/damage_leg_r/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/damage_leg_r/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^-0.3 ^-0.05 ^0
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/damage_leg_r/keyframes/1
execute if entity @s[scores={AsaMatrix=6..14}] run tp @s ^-0.1666667 ^-0.1388889 ^0
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/damage_leg_r/keyframes/2
execute if entity @s[scores={AsaMatrix=15..24}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/damage_leg_r/keyframes/3
execute if entity @s[scores={AsaMatrix=25..38}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/damage_leg_r/keyframes/4
execute if entity @s[scores={AsaMatrix=39..45}] run tp @s ^-0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/damage_leg_r/keyframes/5
execute if entity @s[scores={AsaMatrix=46..55}] run tp @s ^0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/damage_leg_r/keyframes/6
execute if entity @s[scores={AsaMatrix=56..61}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/damage_leg_r/keyframes/7
execute if entity @s[scores={AsaMatrix=62..75}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/damage_leg_r/keyframes/8
execute if entity @s[scores={AsaMatrix=76..82}] run tp @s ^-0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=83}] run function asa_animator:reus/anim/damage_leg_r/keyframes/9
execute if entity @s[scores={AsaMatrix=83..92}] run tp @s ^0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=93}] run function asa_animator:reus/anim/damage_leg_r/keyframes/10
execute if entity @s[scores={AsaMatrix=93..98}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=99}] run function asa_animator:reus/anim/damage_leg_r/keyframes/11
execute if entity @s[scores={AsaMatrix=99..112}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=113}] run function asa_animator:reus/anim/damage_leg_r/keyframes/12
execute if entity @s[scores={AsaMatrix=113..119}] run tp @s ^-0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=120}] run function asa_animator:reus/anim/damage_leg_r/keyframes/13
execute if entity @s[scores={AsaMatrix=120..129}] run tp @s ^0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=130}] run function asa_animator:reus/anim/damage_leg_r/keyframes/14
execute if entity @s[scores={AsaMatrix=130..137}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=138}] run function asa_animator:reus/anim/damage_leg_r/keyframes/15
execute if entity @s[scores={AsaMatrix=138..152}] run tp @s ^0 ^0.06 ^0
execute if entity @s[scores={AsaMatrix=153}] run function asa_animator:reus/anim/damage_leg_r/keyframes/16
execute if entity @s[scores={AsaMatrix=153..167}] run tp @s ^0 ^0.04 ^0
execute if entity @s[scores={AsaMatrix=168..}] run function asa_animator:reus/anim/damage_leg_r/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 演出
    execute if entity @s[scores={AsaMatrix=13..16}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=14}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=24}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=61}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=98}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=137}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.hurt master @a[distance=..48] ~ ~ ~ 0.5 0.7 0.5
    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=24..26}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=61..63}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=98..100}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5

# 高度調整
    execute if entity @s[scores={AsaMatrix=16..112}] at @s if block ~ ~1.5 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=16..112}] at @s unless block ~ ~1.7 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~
