# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^-0.3 ^-0.05 ^0
execute if entity @s[scores={AsaMatrix=6..14}] run tp @s ^-0.1666667 ^-0.1388889 ^0
execute if entity @s[scores={AsaMatrix=15..24}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=25..38}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=39..45}] run tp @s ^-0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=46..55}] run tp @s ^0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=56..61}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=62..75}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=76..82}] run tp @s ^-0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=83..92}] run tp @s ^0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=93..98}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=99..112}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=113..119}] run tp @s ^-0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=120..129}] run tp @s ^0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=130..137}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=138..152}] run tp @s ^0 ^0.06 ^0
execute if entity @s[scores={AsaMatrix=153..167}] run tp @s ^0 ^0.04 ^0

# 演出
    execute if entity @s[scores={AsaMatrix=13..16}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=14}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=24}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=61}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=98}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=137}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.hurt master @a[distance=..48] ~ ~ ~ 0.5 0.7 0.5
    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=24..26}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=61..63}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=98..100}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5

# 高度調整
    execute if entity @s[scores={AsaMatrix=16..112}] at @s if block ~ ~1.5 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=16..112}] at @s unless block ~ ~1.7 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/damage_leg_r/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/damage_leg_r/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/damage_leg_r/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/damage_leg_r/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/damage_leg_r/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/damage_leg_r/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/damage_leg_r/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/damage_leg_r/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/damage_leg_r/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/damage_leg_r/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/damage_leg_r/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/damage_leg_r/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/damage_leg_r/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/damage_leg_r/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/damage_leg_r/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/damage_leg_r/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/damage_leg_r/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/damage_leg_r/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/damage_leg_r/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/damage_leg_r/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/damage_leg_r/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/damage_leg_r/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/damage_leg_r/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/damage_leg_r/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/damage_leg_r/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/damage_leg_r/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/damage_leg_r/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/damage_leg_r/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/damage_leg_r/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/damage_leg_r/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/damage_leg_r/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/damage_leg_r/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/damage_leg_r/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/damage_leg_r/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/damage_leg_r/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/damage_leg_r/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/damage_leg_r/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/damage_leg_r/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/damage_leg_r/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/damage_leg_r/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/damage_leg_r/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/damage_leg_r/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/damage_leg_r/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/damage_leg_r/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/damage_leg_r/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/damage_leg_r/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/damage_leg_r/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/damage_leg_r/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/damage_leg_r/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/damage_leg_r/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/damage_leg_r/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/damage_leg_r/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/damage_leg_r/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/damage_leg_r/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/damage_leg_r/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/damage_leg_r/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/damage_leg_r/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/damage_leg_r/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/damage_leg_r/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/damage_leg_r/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/damage_leg_r/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/damage_leg_r/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/damage_leg_r/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/damage_leg_r/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/damage_leg_r/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/damage_leg_r/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/damage_leg_r/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/damage_leg_r/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/damage_leg_r/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:reus/anim/damage_leg_r/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/damage_leg_r/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:reus/anim/damage_leg_r/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:reus/anim/damage_leg_r/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:reus/anim/damage_leg_r/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:reus/anim/damage_leg_r/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/damage_leg_r/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:reus/anim/damage_leg_r/keyframes/77
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:reus/anim/damage_leg_r/keyframes/78
execute if entity @s[scores={AsaMatrix=79}] run function asa_animator:reus/anim/damage_leg_r/keyframes/79
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:reus/anim/damage_leg_r/keyframes/80
execute if entity @s[scores={AsaMatrix=81}] run function asa_animator:reus/anim/damage_leg_r/keyframes/81
execute if entity @s[scores={AsaMatrix=82}] run function asa_animator:reus/anim/damage_leg_r/keyframes/82
execute if entity @s[scores={AsaMatrix=83}] run function asa_animator:reus/anim/damage_leg_r/keyframes/83
execute if entity @s[scores={AsaMatrix=84}] run function asa_animator:reus/anim/damage_leg_r/keyframes/84
execute if entity @s[scores={AsaMatrix=85}] run function asa_animator:reus/anim/damage_leg_r/keyframes/85
execute if entity @s[scores={AsaMatrix=86}] run function asa_animator:reus/anim/damage_leg_r/keyframes/86
execute if entity @s[scores={AsaMatrix=87}] run function asa_animator:reus/anim/damage_leg_r/keyframes/87
execute if entity @s[scores={AsaMatrix=88}] run function asa_animator:reus/anim/damage_leg_r/keyframes/88
execute if entity @s[scores={AsaMatrix=89}] run function asa_animator:reus/anim/damage_leg_r/keyframes/89
execute if entity @s[scores={AsaMatrix=90}] run function asa_animator:reus/anim/damage_leg_r/keyframes/90
execute if entity @s[scores={AsaMatrix=91}] run function asa_animator:reus/anim/damage_leg_r/keyframes/91
execute if entity @s[scores={AsaMatrix=92}] run function asa_animator:reus/anim/damage_leg_r/keyframes/92
execute if entity @s[scores={AsaMatrix=93}] run function asa_animator:reus/anim/damage_leg_r/keyframes/93
execute if entity @s[scores={AsaMatrix=94}] run function asa_animator:reus/anim/damage_leg_r/keyframes/94
execute if entity @s[scores={AsaMatrix=95}] run function asa_animator:reus/anim/damage_leg_r/keyframes/95
execute if entity @s[scores={AsaMatrix=96}] run function asa_animator:reus/anim/damage_leg_r/keyframes/96
execute if entity @s[scores={AsaMatrix=97}] run function asa_animator:reus/anim/damage_leg_r/keyframes/97
execute if entity @s[scores={AsaMatrix=98}] run function asa_animator:reus/anim/damage_leg_r/keyframes/98
execute if entity @s[scores={AsaMatrix=99}] run function asa_animator:reus/anim/damage_leg_r/keyframes/99
execute if entity @s[scores={AsaMatrix=100}] run function asa_animator:reus/anim/damage_leg_r/keyframes/100
execute if entity @s[scores={AsaMatrix=101}] run function asa_animator:reus/anim/damage_leg_r/keyframes/101
execute if entity @s[scores={AsaMatrix=102}] run function asa_animator:reus/anim/damage_leg_r/keyframes/102
execute if entity @s[scores={AsaMatrix=103}] run function asa_animator:reus/anim/damage_leg_r/keyframes/103
execute if entity @s[scores={AsaMatrix=104}] run function asa_animator:reus/anim/damage_leg_r/keyframes/104
execute if entity @s[scores={AsaMatrix=105}] run function asa_animator:reus/anim/damage_leg_r/keyframes/105
execute if entity @s[scores={AsaMatrix=106}] run function asa_animator:reus/anim/damage_leg_r/keyframes/106
execute if entity @s[scores={AsaMatrix=107}] run function asa_animator:reus/anim/damage_leg_r/keyframes/107
execute if entity @s[scores={AsaMatrix=108}] run function asa_animator:reus/anim/damage_leg_r/keyframes/108
execute if entity @s[scores={AsaMatrix=109}] run function asa_animator:reus/anim/damage_leg_r/keyframes/109
execute if entity @s[scores={AsaMatrix=110}] run function asa_animator:reus/anim/damage_leg_r/keyframes/110
execute if entity @s[scores={AsaMatrix=111}] run function asa_animator:reus/anim/damage_leg_r/keyframes/111
execute if entity @s[scores={AsaMatrix=112}] run function asa_animator:reus/anim/damage_leg_r/keyframes/112
execute if entity @s[scores={AsaMatrix=113}] run function asa_animator:reus/anim/damage_leg_r/keyframes/113
execute if entity @s[scores={AsaMatrix=114}] run function asa_animator:reus/anim/damage_leg_r/keyframes/114
execute if entity @s[scores={AsaMatrix=115}] run function asa_animator:reus/anim/damage_leg_r/keyframes/115
execute if entity @s[scores={AsaMatrix=116}] run function asa_animator:reus/anim/damage_leg_r/keyframes/116
execute if entity @s[scores={AsaMatrix=117}] run function asa_animator:reus/anim/damage_leg_r/keyframes/117
execute if entity @s[scores={AsaMatrix=118}] run function asa_animator:reus/anim/damage_leg_r/keyframes/118
execute if entity @s[scores={AsaMatrix=119}] run function asa_animator:reus/anim/damage_leg_r/keyframes/119
execute if entity @s[scores={AsaMatrix=120}] run function asa_animator:reus/anim/damage_leg_r/keyframes/120
execute if entity @s[scores={AsaMatrix=121}] run function asa_animator:reus/anim/damage_leg_r/keyframes/121
execute if entity @s[scores={AsaMatrix=122}] run function asa_animator:reus/anim/damage_leg_r/keyframes/122
execute if entity @s[scores={AsaMatrix=123}] run function asa_animator:reus/anim/damage_leg_r/keyframes/123
execute if entity @s[scores={AsaMatrix=124}] run function asa_animator:reus/anim/damage_leg_r/keyframes/124
execute if entity @s[scores={AsaMatrix=125}] run function asa_animator:reus/anim/damage_leg_r/keyframes/125
execute if entity @s[scores={AsaMatrix=126}] run function asa_animator:reus/anim/damage_leg_r/keyframes/126
execute if entity @s[scores={AsaMatrix=127}] run function asa_animator:reus/anim/damage_leg_r/keyframes/127
execute if entity @s[scores={AsaMatrix=128}] run function asa_animator:reus/anim/damage_leg_r/keyframes/128
execute if entity @s[scores={AsaMatrix=129}] run function asa_animator:reus/anim/damage_leg_r/keyframes/129
execute if entity @s[scores={AsaMatrix=130}] run function asa_animator:reus/anim/damage_leg_r/keyframes/130
execute if entity @s[scores={AsaMatrix=131}] run function asa_animator:reus/anim/damage_leg_r/keyframes/131
execute if entity @s[scores={AsaMatrix=132}] run function asa_animator:reus/anim/damage_leg_r/keyframes/132
execute if entity @s[scores={AsaMatrix=133}] run function asa_animator:reus/anim/damage_leg_r/keyframes/133
execute if entity @s[scores={AsaMatrix=134}] run function asa_animator:reus/anim/damage_leg_r/keyframes/134
execute if entity @s[scores={AsaMatrix=135}] run function asa_animator:reus/anim/damage_leg_r/keyframes/135
execute if entity @s[scores={AsaMatrix=136}] run function asa_animator:reus/anim/damage_leg_r/keyframes/136
execute if entity @s[scores={AsaMatrix=137}] run function asa_animator:reus/anim/damage_leg_r/keyframes/137
execute if entity @s[scores={AsaMatrix=138}] run function asa_animator:reus/anim/damage_leg_r/keyframes/138
execute if entity @s[scores={AsaMatrix=139}] run function asa_animator:reus/anim/damage_leg_r/keyframes/139
execute if entity @s[scores={AsaMatrix=140}] run function asa_animator:reus/anim/damage_leg_r/keyframes/140
execute if entity @s[scores={AsaMatrix=141}] run function asa_animator:reus/anim/damage_leg_r/keyframes/141
execute if entity @s[scores={AsaMatrix=142}] run function asa_animator:reus/anim/damage_leg_r/keyframes/142
execute if entity @s[scores={AsaMatrix=143}] run function asa_animator:reus/anim/damage_leg_r/keyframes/143
execute if entity @s[scores={AsaMatrix=144}] run function asa_animator:reus/anim/damage_leg_r/keyframes/144
execute if entity @s[scores={AsaMatrix=145}] run function asa_animator:reus/anim/damage_leg_r/keyframes/145
execute if entity @s[scores={AsaMatrix=146}] run function asa_animator:reus/anim/damage_leg_r/keyframes/146
execute if entity @s[scores={AsaMatrix=147}] run function asa_animator:reus/anim/damage_leg_r/keyframes/147
execute if entity @s[scores={AsaMatrix=148}] run function asa_animator:reus/anim/damage_leg_r/keyframes/148
execute if entity @s[scores={AsaMatrix=149}] run function asa_animator:reus/anim/damage_leg_r/keyframes/149
execute if entity @s[scores={AsaMatrix=150}] run function asa_animator:reus/anim/damage_leg_r/keyframes/150
execute if entity @s[scores={AsaMatrix=151}] run function asa_animator:reus/anim/damage_leg_r/keyframes/151
execute if entity @s[scores={AsaMatrix=152}] run function asa_animator:reus/anim/damage_leg_r/keyframes/152
execute if entity @s[scores={AsaMatrix=153}] run function asa_animator:reus/anim/damage_leg_r/keyframes/153
execute if entity @s[scores={AsaMatrix=154}] run function asa_animator:reus/anim/damage_leg_r/keyframes/154
execute if entity @s[scores={AsaMatrix=155}] run function asa_animator:reus/anim/damage_leg_r/keyframes/155
execute if entity @s[scores={AsaMatrix=156}] run function asa_animator:reus/anim/damage_leg_r/keyframes/156
execute if entity @s[scores={AsaMatrix=157}] run function asa_animator:reus/anim/damage_leg_r/keyframes/157
execute if entity @s[scores={AsaMatrix=158}] run function asa_animator:reus/anim/damage_leg_r/keyframes/158
execute if entity @s[scores={AsaMatrix=159}] run function asa_animator:reus/anim/damage_leg_r/keyframes/159
execute if entity @s[scores={AsaMatrix=160}] run function asa_animator:reus/anim/damage_leg_r/keyframes/160
execute if entity @s[scores={AsaMatrix=161}] run function asa_animator:reus/anim/damage_leg_r/keyframes/161
execute if entity @s[scores={AsaMatrix=162}] run function asa_animator:reus/anim/damage_leg_r/keyframes/162
execute if entity @s[scores={AsaMatrix=163}] run function asa_animator:reus/anim/damage_leg_r/keyframes/163
execute if entity @s[scores={AsaMatrix=164}] run function asa_animator:reus/anim/damage_leg_r/keyframes/164
execute if entity @s[scores={AsaMatrix=165}] run function asa_animator:reus/anim/damage_leg_r/keyframes/165
execute if entity @s[scores={AsaMatrix=166}] run function asa_animator:reus/anim/damage_leg_r/keyframes/166
execute if entity @s[scores={AsaMatrix=167..}] run function asa_animator:reus/anim/damage_leg_r/keyframes/167
execute if entity @s[scores={AsaMatrix=168..}] run function asa_animator:reus/anim/damage_leg_r/end
function asa_animator:reus/model
