# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..12}] run tp @s ^0.00 ^-0.05 ^0.00
execute if entity @s[scores={AsaMatrix=13..24}] run tp @s ^0.00 ^0.05 ^0.02
execute if entity @s[scores={AsaMatrix=25..36}] run tp @s ^0.00 ^-0.05 ^-0.01
execute if entity @s[scores={AsaMatrix=37..48}] run tp @s ^0.00 ^0.05 ^-0.01

# 遷移
    execute if entity @s[scores={AsaMatrix=1}] if entity @e[tag=ReusTarget] run function asa_animator:reus/anim/stay/events/change
    execute if entity @s[scores={AsaMatrix=1}] if entity @e[tag=MnsTarget] run function asa_animator:reus/anim/stay/events/change

# 演出
    execute if entity @s[scores={AsaMatrix=10}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=34}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    
# 高度調整
    execute at @s if block ~ ~-3 ~ #asa_animator:no_collision at @s run tp @s ~ ~-0.5 ~ ~ ~
    execute at @s unless block ~ ~-2 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.5 ~ ~ ~

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/flying_stay/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/flying_stay/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/flying_stay/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/flying_stay/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/flying_stay/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_stay/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/flying_stay/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_stay/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_stay/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/flying_stay/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_stay/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/flying_stay/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/flying_stay/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/flying_stay/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/flying_stay/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/flying_stay/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_stay/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/flying_stay/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/flying_stay/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/flying_stay/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/flying_stay/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/flying_stay/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/flying_stay/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/flying_stay/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/flying_stay/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/flying_stay/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/flying_stay/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/flying_stay/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/flying_stay/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/flying_stay/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/flying_stay/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/flying_stay/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/flying_stay/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/flying_stay/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/flying_stay/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/flying_stay/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/flying_stay/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/flying_stay/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/flying_stay/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/flying_stay/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/flying_stay/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/flying_stay/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/flying_stay/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/flying_stay/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/flying_stay/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/flying_stay/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/flying_stay/keyframes/47
execute if entity @s[scores={AsaMatrix=48..}] run function asa_animator:reus/anim/flying_stay/keyframes/48
execute if entity @s[scores={AsaMatrix=49..}] run function asa_animator:reus/anim/flying_stay/end
function asa_animator:reus/model
