# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^-0.07142857 ^0.1428571 ^-0.1428571
execute if entity @s[scores={AsaMatrix=8..10}] run tp @s ^-0.09999999 ^0.125 ^-0.0625
execute if entity @s[scores={AsaMatrix=11..15}] run tp @s ^-0.09999999 ^0.125 ^-0.0625 ~-15 ~
execute if entity @s[scores={AsaMatrix=16..21}] run tp @s ^0 ^0.07 ^0
execute if entity @s[scores={AsaMatrix=22..27}] run tp @s ^0 ^-0.07 ^0
execute if entity @s[scores={AsaMatrix=28..33}] run tp @s ^0 ^0.07 ^0
execute if entity @s[scores={AsaMatrix=34..39}] run tp @s ^0 ^-0.07 ^0
execute if entity @s[scores={AsaMatrix=40..45}] run tp @s ^0 ^0.07 ^0
execute if entity @s[scores={AsaMatrix=46..52}] run tp @s ^0 ^-0.0142857 ^-0.07142857 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=53..59}] run tp @s ^0.1142857 ^0.07142857 ^-0.1428571
execute if entity @s[scores={AsaMatrix=60..69}] run tp @s ^0.05 ^-0.15 ^-0.1
execute if entity @s[scores={AsaMatrix=70..79}] run tp @s ^0 ^-0.15 ^-0.08000002

# 移動
    execute if entity @s[scores={AsaMatrix=1..10}] run function asa_animator:reus/manager/4_general/rotate
    execute if entity @s[scores={AsaMatrix=44..52}] run function asa_animator:reus/manager/4_general/rotate_fast

# 演出
    execute if entity @s[scores={AsaMatrix=1..29}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..12] at @s positioned ^ ^1.3 ^0.8 run particle flame ~ ~ ~ 0.2 0.2 0.2 0.1 3
    execute if entity @s[scores={AsaMatrix=1}] run playsound entity.player.breath master @a ~ ~ ~ 2 0.8
    execute if entity @s[scores={AsaMatrix=15}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=27}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=39}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=52}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

# 攻撃
    # 攻撃用Marker召喚
        execute if entity @s[scores={AsaMatrix=15}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..7] at @s run function asa_animator:reus/anim/flying_breath_charge/events/attack_start
    # 予備動作（判定あり）
        execute if entity @s[scores={AsaMatrix=16..45}] as @e[type=marker,tag=ReusChargeFPos,distance=0..7] at @s run function asa_animator:reus/anim/flying_breath_charge/events/attack
    # 攻撃
        execute if entity @s[scores={AsaMatrix=43}] as @e[type=marker,tag=ReusChargeFPos] facing entity @e[tag=ReusAttackTarget] eyes run tp @s ~ ~ ~ ~ 90
        execute if entity @s[scores={AsaMatrix=46..58}] as @e[type=marker,tag=ReusChargeFPos,distance=0..7] at @s run function asa_animator:reus/anim/flying_breath_charge/events/attack_rotate
    # 終了
        execute if entity @s[scores={AsaMatrix=59}] run kill @e[type=marker,tag=ReusChargeFPos]

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/77
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/78
execute if entity @s[scores={AsaMatrix=79..}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/79
execute if entity @s[scores={AsaMatrix=80..}] run function asa_animator:reus/anim/flying_breath_charge/end
function asa_animator:reus/model
