# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_move_breath_r/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0.125 ^-0.075
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/1
execute if entity @s[scores={AsaMatrix=9..16}] run tp @s ^0.3 ^-0.125 ^0.175
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/2
execute if entity @s[scores={AsaMatrix=17..32}] run tp @s ^0.1 ^0 ^0
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/3
execute if entity @s[scores={AsaMatrix=33..38}] run tp @s ^-0.1 ^0.08333334 ^0
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/4
execute if entity @s[scores={AsaMatrix=39..44}] run tp @s ^0 ^-0.08333334 ^-0.01666667
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/5
execute if entity @s[scores={AsaMatrix=45..50}] run tp @s ^0 ^0.02777778 ^-0.1555555
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/6
execute if entity @s[scores={AsaMatrix=51..56}] run tp @s ^0 ^0.02777777 ^-0.1555556
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/7
execute if entity @s[scores={AsaMatrix=57..62}] run tp @s ^0 ^-0.2 ^-0.1555555
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/flying_move_breath_r/keyframes/8
execute if entity @s[scores={AsaMatrix=63..74}] run tp @s ^0 ^-0.2 ^-0.07500001
execute if entity @s[scores={AsaMatrix=75..}] run function asa_animator:reus/anim/flying_move_breath_r/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 移動
    execute if entity @s[scores={AsaMatrix=1..10}] run function asa_animator:reus/manager/4_general/rotate
    execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_move_breath_r/events/pos/set_pos_0
    execute if entity @s[scores={AsaMatrix=9..44}] run function asa_animator:reus/anim/flying_move_breath_r/events/pos/offset
    execute if entity @s[scores={AsaMatrix=32..}] run function asa_animator:reus/manager/4_general/rotate
    execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/flying_move_breath_r/events/pos/set_pos_1
    execute if entity @s[scores={AsaMatrix=45..62}] run function asa_animator:reus/anim/flying_move_breath_r/events/pos/offset

# 演出
    execute if entity @s[scores={AsaMatrix=8}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=32}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=50}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=62}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

# 発射位置決定
    execute if entity @s[scores={AsaMatrix=38}] run summon marker ^ ^0.7 ^8 {Tags:["ReusBreathTarget"]}
    execute if entity @s[scores={AsaMatrix=38}] unless entity @e[tag=ReusAttackTarget,distance=0..12] at @e[tag=ReusAttackTarget,limit=1] run tp @e[type=marker,tag=ReusBreathTarget] ~ ~1 ~
# ブレス発射
    execute if entity @s[scores={AsaMatrix=44}] positioned ^5 ^3 ^4.5 facing entity @e[type=marker,tag=ReusBreathTarget,limit=1] feet run function asa_animator:reus/anim/breath/events/shot
