# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/damage_tail_destroy/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/0
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0.03333334 ^0.8 ~-1 ~
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/1
execute if entity @s[scores={AsaMatrix=7..12}] run tp @s ^-0.08333334 ^-0.03333334 ^0.8 ~-2 ~
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/2
execute if entity @s[scores={AsaMatrix=13..18}] run tp @s ^-0.08333334 ^-0.05 ^0.8 ~-5 ~
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/3
execute if entity @s[scores={AsaMatrix=19..25}] run tp @s ^0 ^0 ^-0.1 ~-15 ~
execute if entity @s[scores={AsaMatrix=26..45}] run tp @s ^0 ^0 ^-0.1 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/4
execute if entity @s[scores={AsaMatrix=46..60}] run tp @s ^0 ^-0.01333333 ^-0.06666667 ~-0.1 ~
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/5
execute if entity @s[scores={AsaMatrix=61..70}] run tp @s ^0 ^0.03 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/6
execute if entity @s[scores={AsaMatrix=71..80}] run tp @s ^0 ^0.02 ^0 ~0.5 ~
execute if entity @s[scores={AsaMatrix=81..}] run function asa_animator:reus/anim/damage_tail_destroy/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 演出
    execute if entity @s[scores={AsaMatrix=18..35}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=18..35}] run particle block grass_block ~ ~ ~ 1 0.1 1 0 10
    execute if entity @s[scores={AsaMatrix=18}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7

    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.hurt master @a[distance=..48] ~ ~ ~ 0.5 0.7 0.5
    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5

# 高度調整
    execute if entity @s[scores={AsaMatrix=1..18}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=1..18}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=71..80}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=71..80}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~
