# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0.03333334 ^0.8 ~-1 ~
execute if entity @s[scores={AsaMatrix=7..12}] run tp @s ^-0.08333334 ^-0.03333334 ^0.8 ~-2 ~
execute if entity @s[scores={AsaMatrix=13..18}] run tp @s ^-0.08333334 ^-0.05 ^0.8 ~-5 ~
execute if entity @s[scores={AsaMatrix=19..25}] run tp @s ^0 ^0 ^-0.1 ~-15 ~
execute if entity @s[scores={AsaMatrix=26..45}] run tp @s ^0 ^0 ^-0.1 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=46..60}] run tp @s ^0 ^-0.01333333 ^-0.06666667 ~-0.1 ~
execute if entity @s[scores={AsaMatrix=61..70}] run tp @s ^0 ^0.03 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=71..80}] run tp @s ^0 ^0.02 ^0 ~0.5 ~

# 演出
    execute if entity @s[scores={AsaMatrix=18..35}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=18..35}] run particle block grass_block ~ ~ ~ 1 0.1 1 0 10
    execute if entity @s[scores={AsaMatrix=18}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7

    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.hurt master @a[distance=..48] ~ ~ ~ 0.5 0.7 0.5
    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5

# 高度調整
    execute if entity @s[scores={AsaMatrix=1..18}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=1..18}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=71..80}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=71..80}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/77
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/78
execute if entity @s[scores={AsaMatrix=79}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/79
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/80
execute if entity @s[scores={AsaMatrix=81..}] run function asa_animator:reus/anim/damage_tail_destroy/keyframes/81
execute if entity @s[scores={AsaMatrix=81..}] run function asa_animator:reus/anim/damage_tail_destroy/end
function asa_animator:reus/model
