# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_move_land_l/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_move_land_l/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^-0.0625 ^0
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_move_land_l/keyframes/1
execute if entity @s[scores={AsaMatrix=9..13}] run tp @s ^0 ^0.2 ^0
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/flying_move_land_l/keyframes/2
execute if entity @s[scores={AsaMatrix=14..18}] run tp @s ^0.5 ^0.18 ^0
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/flying_move_land_l/keyframes/3
execute if entity @s[scores={AsaMatrix=19..23}] run tp @s ^0.2 ^-0.34 ^0
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/flying_move_land_l/keyframes/4
execute if entity @s[scores={AsaMatrix=24..33}] run tp @s ^0.2 ^0.02999999 ^0.2
execute if entity @s[scores={AsaMatrix=26..}] run function asa_animator:reus/anim/flying_move_land_l/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 移動
    function asa_animator:reus/manager/4_general/rotate_fast
    execute if entity @s[scores={AsaMatrix=1}] facing entity @e[tag=ReusAttackTarget,limit=1] feet rotated ~ 0 run function asa_animator:reus/anim/flying_move_land_l/events/pos/set_pos_0
    execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/flying_move_land_l/events/pos/set_pos_1
    execute if entity @s[scores={AsaMatrix=1..14}] at @s run function asa_animator:reus/anim/flying_move_land_l/events/pos/offset

# 演出
    execute if entity @s[scores={AsaMatrix=6}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=22}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=22..}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/manager/5_extra/change_to_normal
