# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0.3 ^-0.05 ^0
execute if entity @s[scores={AsaMatrix=6..14}] run tp @s ^0.1666667 ^-0.1388889 ^0
execute if entity @s[scores={AsaMatrix=15..24}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=25..38}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=39..45}] run tp @s ^0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=46..55}] run tp @s ^-0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=56..61}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=62..75}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=76..82}] run tp @s ^0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=83..92}] run tp @s ^-0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=93..98}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=99..112}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=113..119}] run tp @s ^0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=120..129}] run tp @s ^-0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=130..135}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=136..149}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=150..156}] run tp @s ^0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=157..166}] run tp @s ^-0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=167..172}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=173..186}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=187..193}] run tp @s ^0.0142857 ^0 ^0
execute if entity @s[scores={AsaMatrix=194..203}] run tp @s ^-0.00999999 ^0 ^0
execute if entity @s[scores={AsaMatrix=204..209}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=210..224}] run tp @s ^0 ^0.06 ^0
execute if entity @s[scores={AsaMatrix=225..239}] run tp @s ^0 ^0.04 ^0

# 演出
    execute if entity @s[scores={AsaMatrix=1..210}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..12] at @s positioned ^ ^2.5 ^0.5 run particle crit ^ ^ ^ 0.3 0.1 0.3 0.1 1

    execute if entity @s[scores={AsaMatrix=13..16}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=14}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=24}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=61}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=98}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=210}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.hurt master @a[distance=..48] ~ ~ ~ 0.5 0.7 0.5
    execute if entity @s[scores={AsaMatrix=1..5}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=24..26}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=61..63}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=98..100}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=135..137}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5
    execute if entity @s[scores={AsaMatrix=172..174}] run playsound entity.ravager.attack master @a[distance=..48] ~ ~ ~ 0.5 0.82 0.5

# 高度調整
    execute if entity @s[scores={AsaMatrix=1}] at @s run tp @s ~ ~5 ~
    execute if entity @s[scores={AsaMatrix=1}] at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=16..210}] at @s if block ~ ~1.5 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=16..210}] at @s unless block ~ ~1.7 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/damage_stun/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/damage_stun/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/damage_stun/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/damage_stun/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/damage_stun/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/damage_stun/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/damage_stun/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/damage_stun/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/damage_stun/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/damage_stun/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/damage_stun/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/damage_stun/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/damage_stun/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/damage_stun/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/damage_stun/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/damage_stun/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/damage_stun/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/damage_stun/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/damage_stun/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/damage_stun/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/damage_stun/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/damage_stun/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/damage_stun/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/damage_stun/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/damage_stun/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/damage_stun/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/damage_stun/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/damage_stun/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/damage_stun/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/damage_stun/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/damage_stun/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/damage_stun/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/damage_stun/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/damage_stun/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/damage_stun/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/damage_stun/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/damage_stun/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/damage_stun/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/damage_stun/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/damage_stun/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/damage_stun/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/damage_stun/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/damage_stun/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/damage_stun/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/damage_stun/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/damage_stun/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/damage_stun/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/damage_stun/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/damage_stun/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/damage_stun/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/damage_stun/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/damage_stun/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/damage_stun/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/damage_stun/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/damage_stun/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/damage_stun/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/damage_stun/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/damage_stun/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/damage_stun/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:reus/anim/damage_stun/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/damage_stun/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:reus/anim/damage_stun/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:reus/anim/damage_stun/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/damage_stun/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:reus/anim/damage_stun/keyframes/65
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/damage_stun/keyframes/66
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:reus/anim/damage_stun/keyframes/67
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:reus/anim/damage_stun/keyframes/68
execute if entity @s[scores={AsaMatrix=69}] run function asa_animator:reus/anim/damage_stun/keyframes/69
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:reus/anim/damage_stun/keyframes/70
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:reus/anim/damage_stun/keyframes/71
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:reus/anim/damage_stun/keyframes/72
execute if entity @s[scores={AsaMatrix=73}] run function asa_animator:reus/anim/damage_stun/keyframes/73
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:reus/anim/damage_stun/keyframes/74
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:reus/anim/damage_stun/keyframes/75
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/damage_stun/keyframes/76
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:reus/anim/damage_stun/keyframes/77
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:reus/anim/damage_stun/keyframes/78
execute if entity @s[scores={AsaMatrix=79}] run function asa_animator:reus/anim/damage_stun/keyframes/79
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:reus/anim/damage_stun/keyframes/80
execute if entity @s[scores={AsaMatrix=81}] run function asa_animator:reus/anim/damage_stun/keyframes/81
execute if entity @s[scores={AsaMatrix=82}] run function asa_animator:reus/anim/damage_stun/keyframes/82
execute if entity @s[scores={AsaMatrix=83}] run function asa_animator:reus/anim/damage_stun/keyframes/83
execute if entity @s[scores={AsaMatrix=84}] run function asa_animator:reus/anim/damage_stun/keyframes/84
execute if entity @s[scores={AsaMatrix=85}] run function asa_animator:reus/anim/damage_stun/keyframes/85
execute if entity @s[scores={AsaMatrix=86}] run function asa_animator:reus/anim/damage_stun/keyframes/86
execute if entity @s[scores={AsaMatrix=87}] run function asa_animator:reus/anim/damage_stun/keyframes/87
execute if entity @s[scores={AsaMatrix=88}] run function asa_animator:reus/anim/damage_stun/keyframes/88
execute if entity @s[scores={AsaMatrix=89}] run function asa_animator:reus/anim/damage_stun/keyframes/89
execute if entity @s[scores={AsaMatrix=90}] run function asa_animator:reus/anim/damage_stun/keyframes/90
execute if entity @s[scores={AsaMatrix=91}] run function asa_animator:reus/anim/damage_stun/keyframes/91
execute if entity @s[scores={AsaMatrix=92}] run function asa_animator:reus/anim/damage_stun/keyframes/92
execute if entity @s[scores={AsaMatrix=93}] run function asa_animator:reus/anim/damage_stun/keyframes/93
execute if entity @s[scores={AsaMatrix=94}] run function asa_animator:reus/anim/damage_stun/keyframes/94
execute if entity @s[scores={AsaMatrix=95}] run function asa_animator:reus/anim/damage_stun/keyframes/95
execute if entity @s[scores={AsaMatrix=96}] run function asa_animator:reus/anim/damage_stun/keyframes/96
execute if entity @s[scores={AsaMatrix=97}] run function asa_animator:reus/anim/damage_stun/keyframes/97
execute if entity @s[scores={AsaMatrix=98}] run function asa_animator:reus/anim/damage_stun/keyframes/98
execute if entity @s[scores={AsaMatrix=99}] run function asa_animator:reus/anim/damage_stun/keyframes/99
execute if entity @s[scores={AsaMatrix=100}] run function asa_animator:reus/anim/damage_stun/keyframes/100
execute if entity @s[scores={AsaMatrix=101}] run function asa_animator:reus/anim/damage_stun/keyframes/101
execute if entity @s[scores={AsaMatrix=102}] run function asa_animator:reus/anim/damage_stun/keyframes/102
execute if entity @s[scores={AsaMatrix=103}] run function asa_animator:reus/anim/damage_stun/keyframes/103
execute if entity @s[scores={AsaMatrix=104}] run function asa_animator:reus/anim/damage_stun/keyframes/104
execute if entity @s[scores={AsaMatrix=105}] run function asa_animator:reus/anim/damage_stun/keyframes/105
execute if entity @s[scores={AsaMatrix=106}] run function asa_animator:reus/anim/damage_stun/keyframes/106
execute if entity @s[scores={AsaMatrix=107}] run function asa_animator:reus/anim/damage_stun/keyframes/107
execute if entity @s[scores={AsaMatrix=108}] run function asa_animator:reus/anim/damage_stun/keyframes/108
execute if entity @s[scores={AsaMatrix=109}] run function asa_animator:reus/anim/damage_stun/keyframes/109
execute if entity @s[scores={AsaMatrix=110}] run function asa_animator:reus/anim/damage_stun/keyframes/110
execute if entity @s[scores={AsaMatrix=111}] run function asa_animator:reus/anim/damage_stun/keyframes/111
execute if entity @s[scores={AsaMatrix=112}] run function asa_animator:reus/anim/damage_stun/keyframes/112
execute if entity @s[scores={AsaMatrix=113}] run function asa_animator:reus/anim/damage_stun/keyframes/113
execute if entity @s[scores={AsaMatrix=114}] run function asa_animator:reus/anim/damage_stun/keyframes/114
execute if entity @s[scores={AsaMatrix=115}] run function asa_animator:reus/anim/damage_stun/keyframes/115
execute if entity @s[scores={AsaMatrix=116}] run function asa_animator:reus/anim/damage_stun/keyframes/116
execute if entity @s[scores={AsaMatrix=117}] run function asa_animator:reus/anim/damage_stun/keyframes/117
execute if entity @s[scores={AsaMatrix=118}] run function asa_animator:reus/anim/damage_stun/keyframes/118
execute if entity @s[scores={AsaMatrix=119}] run function asa_animator:reus/anim/damage_stun/keyframes/119
execute if entity @s[scores={AsaMatrix=120}] run function asa_animator:reus/anim/damage_stun/keyframes/120
execute if entity @s[scores={AsaMatrix=121}] run function asa_animator:reus/anim/damage_stun/keyframes/121
execute if entity @s[scores={AsaMatrix=122}] run function asa_animator:reus/anim/damage_stun/keyframes/122
execute if entity @s[scores={AsaMatrix=123}] run function asa_animator:reus/anim/damage_stun/keyframes/123
execute if entity @s[scores={AsaMatrix=124}] run function asa_animator:reus/anim/damage_stun/keyframes/124
execute if entity @s[scores={AsaMatrix=125}] run function asa_animator:reus/anim/damage_stun/keyframes/125
execute if entity @s[scores={AsaMatrix=126}] run function asa_animator:reus/anim/damage_stun/keyframes/126
execute if entity @s[scores={AsaMatrix=127}] run function asa_animator:reus/anim/damage_stun/keyframes/127
execute if entity @s[scores={AsaMatrix=128}] run function asa_animator:reus/anim/damage_stun/keyframes/128
execute if entity @s[scores={AsaMatrix=129}] run function asa_animator:reus/anim/damage_stun/keyframes/129
execute if entity @s[scores={AsaMatrix=130}] run function asa_animator:reus/anim/damage_stun/keyframes/130
execute if entity @s[scores={AsaMatrix=131}] run function asa_animator:reus/anim/damage_stun/keyframes/131
execute if entity @s[scores={AsaMatrix=132}] run function asa_animator:reus/anim/damage_stun/keyframes/132
execute if entity @s[scores={AsaMatrix=133}] run function asa_animator:reus/anim/damage_stun/keyframes/133
execute if entity @s[scores={AsaMatrix=134}] run function asa_animator:reus/anim/damage_stun/keyframes/134
execute if entity @s[scores={AsaMatrix=135}] run function asa_animator:reus/anim/damage_stun/keyframes/135
execute if entity @s[scores={AsaMatrix=136}] run function asa_animator:reus/anim/damage_stun/keyframes/136
execute if entity @s[scores={AsaMatrix=137}] run function asa_animator:reus/anim/damage_stun/keyframes/137
execute if entity @s[scores={AsaMatrix=138}] run function asa_animator:reus/anim/damage_stun/keyframes/138
execute if entity @s[scores={AsaMatrix=139}] run function asa_animator:reus/anim/damage_stun/keyframes/139
execute if entity @s[scores={AsaMatrix=140}] run function asa_animator:reus/anim/damage_stun/keyframes/140
execute if entity @s[scores={AsaMatrix=141}] run function asa_animator:reus/anim/damage_stun/keyframes/141
execute if entity @s[scores={AsaMatrix=142}] run function asa_animator:reus/anim/damage_stun/keyframes/142
execute if entity @s[scores={AsaMatrix=143}] run function asa_animator:reus/anim/damage_stun/keyframes/143
execute if entity @s[scores={AsaMatrix=144}] run function asa_animator:reus/anim/damage_stun/keyframes/144
execute if entity @s[scores={AsaMatrix=145}] run function asa_animator:reus/anim/damage_stun/keyframes/145
execute if entity @s[scores={AsaMatrix=146}] run function asa_animator:reus/anim/damage_stun/keyframes/146
execute if entity @s[scores={AsaMatrix=147}] run function asa_animator:reus/anim/damage_stun/keyframes/147
execute if entity @s[scores={AsaMatrix=148}] run function asa_animator:reus/anim/damage_stun/keyframes/148
execute if entity @s[scores={AsaMatrix=149}] run function asa_animator:reus/anim/damage_stun/keyframes/149
execute if entity @s[scores={AsaMatrix=150}] run function asa_animator:reus/anim/damage_stun/keyframes/150
execute if entity @s[scores={AsaMatrix=151}] run function asa_animator:reus/anim/damage_stun/keyframes/151
execute if entity @s[scores={AsaMatrix=152}] run function asa_animator:reus/anim/damage_stun/keyframes/152
execute if entity @s[scores={AsaMatrix=153}] run function asa_animator:reus/anim/damage_stun/keyframes/153
execute if entity @s[scores={AsaMatrix=154}] run function asa_animator:reus/anim/damage_stun/keyframes/154
execute if entity @s[scores={AsaMatrix=155}] run function asa_animator:reus/anim/damage_stun/keyframes/155
execute if entity @s[scores={AsaMatrix=156}] run function asa_animator:reus/anim/damage_stun/keyframes/156
execute if entity @s[scores={AsaMatrix=157}] run function asa_animator:reus/anim/damage_stun/keyframes/157
execute if entity @s[scores={AsaMatrix=158}] run function asa_animator:reus/anim/damage_stun/keyframes/158
execute if entity @s[scores={AsaMatrix=159}] run function asa_animator:reus/anim/damage_stun/keyframes/159
execute if entity @s[scores={AsaMatrix=160}] run function asa_animator:reus/anim/damage_stun/keyframes/160
execute if entity @s[scores={AsaMatrix=161}] run function asa_animator:reus/anim/damage_stun/keyframes/161
execute if entity @s[scores={AsaMatrix=162}] run function asa_animator:reus/anim/damage_stun/keyframes/162
execute if entity @s[scores={AsaMatrix=163}] run function asa_animator:reus/anim/damage_stun/keyframes/163
execute if entity @s[scores={AsaMatrix=164}] run function asa_animator:reus/anim/damage_stun/keyframes/164
execute if entity @s[scores={AsaMatrix=165}] run function asa_animator:reus/anim/damage_stun/keyframes/165
execute if entity @s[scores={AsaMatrix=166}] run function asa_animator:reus/anim/damage_stun/keyframes/166
execute if entity @s[scores={AsaMatrix=167}] run function asa_animator:reus/anim/damage_stun/keyframes/167
execute if entity @s[scores={AsaMatrix=168}] run function asa_animator:reus/anim/damage_stun/keyframes/168
execute if entity @s[scores={AsaMatrix=169}] run function asa_animator:reus/anim/damage_stun/keyframes/169
execute if entity @s[scores={AsaMatrix=170}] run function asa_animator:reus/anim/damage_stun/keyframes/170
execute if entity @s[scores={AsaMatrix=171}] run function asa_animator:reus/anim/damage_stun/keyframes/171
execute if entity @s[scores={AsaMatrix=172}] run function asa_animator:reus/anim/damage_stun/keyframes/172
execute if entity @s[scores={AsaMatrix=173}] run function asa_animator:reus/anim/damage_stun/keyframes/173
execute if entity @s[scores={AsaMatrix=174}] run function asa_animator:reus/anim/damage_stun/keyframes/174
execute if entity @s[scores={AsaMatrix=175}] run function asa_animator:reus/anim/damage_stun/keyframes/175
execute if entity @s[scores={AsaMatrix=176}] run function asa_animator:reus/anim/damage_stun/keyframes/176
execute if entity @s[scores={AsaMatrix=177}] run function asa_animator:reus/anim/damage_stun/keyframes/177
execute if entity @s[scores={AsaMatrix=178}] run function asa_animator:reus/anim/damage_stun/keyframes/178
execute if entity @s[scores={AsaMatrix=179}] run function asa_animator:reus/anim/damage_stun/keyframes/179
execute if entity @s[scores={AsaMatrix=180}] run function asa_animator:reus/anim/damage_stun/keyframes/180
execute if entity @s[scores={AsaMatrix=181}] run function asa_animator:reus/anim/damage_stun/keyframes/181
execute if entity @s[scores={AsaMatrix=182}] run function asa_animator:reus/anim/damage_stun/keyframes/182
execute if entity @s[scores={AsaMatrix=183}] run function asa_animator:reus/anim/damage_stun/keyframes/183
execute if entity @s[scores={AsaMatrix=184}] run function asa_animator:reus/anim/damage_stun/keyframes/184
execute if entity @s[scores={AsaMatrix=185}] run function asa_animator:reus/anim/damage_stun/keyframes/185
execute if entity @s[scores={AsaMatrix=186}] run function asa_animator:reus/anim/damage_stun/keyframes/186
execute if entity @s[scores={AsaMatrix=187}] run function asa_animator:reus/anim/damage_stun/keyframes/187
execute if entity @s[scores={AsaMatrix=188}] run function asa_animator:reus/anim/damage_stun/keyframes/188
execute if entity @s[scores={AsaMatrix=189}] run function asa_animator:reus/anim/damage_stun/keyframes/189
execute if entity @s[scores={AsaMatrix=190}] run function asa_animator:reus/anim/damage_stun/keyframes/190
execute if entity @s[scores={AsaMatrix=191}] run function asa_animator:reus/anim/damage_stun/keyframes/191
execute if entity @s[scores={AsaMatrix=192}] run function asa_animator:reus/anim/damage_stun/keyframes/192
execute if entity @s[scores={AsaMatrix=193}] run function asa_animator:reus/anim/damage_stun/keyframes/193
execute if entity @s[scores={AsaMatrix=194}] run function asa_animator:reus/anim/damage_stun/keyframes/194
execute if entity @s[scores={AsaMatrix=195}] run function asa_animator:reus/anim/damage_stun/keyframes/195
execute if entity @s[scores={AsaMatrix=196}] run function asa_animator:reus/anim/damage_stun/keyframes/196
execute if entity @s[scores={AsaMatrix=197}] run function asa_animator:reus/anim/damage_stun/keyframes/197
execute if entity @s[scores={AsaMatrix=198}] run function asa_animator:reus/anim/damage_stun/keyframes/198
execute if entity @s[scores={AsaMatrix=199}] run function asa_animator:reus/anim/damage_stun/keyframes/199
execute if entity @s[scores={AsaMatrix=200}] run function asa_animator:reus/anim/damage_stun/keyframes/200
execute if entity @s[scores={AsaMatrix=201}] run function asa_animator:reus/anim/damage_stun/keyframes/201
execute if entity @s[scores={AsaMatrix=202}] run function asa_animator:reus/anim/damage_stun/keyframes/202
execute if entity @s[scores={AsaMatrix=203}] run function asa_animator:reus/anim/damage_stun/keyframes/203
execute if entity @s[scores={AsaMatrix=204}] run function asa_animator:reus/anim/damage_stun/keyframes/204
execute if entity @s[scores={AsaMatrix=205}] run function asa_animator:reus/anim/damage_stun/keyframes/205
execute if entity @s[scores={AsaMatrix=206}] run function asa_animator:reus/anim/damage_stun/keyframes/206
execute if entity @s[scores={AsaMatrix=207}] run function asa_animator:reus/anim/damage_stun/keyframes/207
execute if entity @s[scores={AsaMatrix=208}] run function asa_animator:reus/anim/damage_stun/keyframes/208
execute if entity @s[scores={AsaMatrix=209}] run function asa_animator:reus/anim/damage_stun/keyframes/209
execute if entity @s[scores={AsaMatrix=210}] run function asa_animator:reus/anim/damage_stun/keyframes/210
execute if entity @s[scores={AsaMatrix=211}] run function asa_animator:reus/anim/damage_stun/keyframes/211
execute if entity @s[scores={AsaMatrix=212}] run function asa_animator:reus/anim/damage_stun/keyframes/212
execute if entity @s[scores={AsaMatrix=213}] run function asa_animator:reus/anim/damage_stun/keyframes/213
execute if entity @s[scores={AsaMatrix=214}] run function asa_animator:reus/anim/damage_stun/keyframes/214
execute if entity @s[scores={AsaMatrix=215}] run function asa_animator:reus/anim/damage_stun/keyframes/215
execute if entity @s[scores={AsaMatrix=216}] run function asa_animator:reus/anim/damage_stun/keyframes/216
execute if entity @s[scores={AsaMatrix=217}] run function asa_animator:reus/anim/damage_stun/keyframes/217
execute if entity @s[scores={AsaMatrix=218}] run function asa_animator:reus/anim/damage_stun/keyframes/218
execute if entity @s[scores={AsaMatrix=219}] run function asa_animator:reus/anim/damage_stun/keyframes/219
execute if entity @s[scores={AsaMatrix=220}] run function asa_animator:reus/anim/damage_stun/keyframes/220
execute if entity @s[scores={AsaMatrix=221}] run function asa_animator:reus/anim/damage_stun/keyframes/221
execute if entity @s[scores={AsaMatrix=222}] run function asa_animator:reus/anim/damage_stun/keyframes/222
execute if entity @s[scores={AsaMatrix=223}] run function asa_animator:reus/anim/damage_stun/keyframes/223
execute if entity @s[scores={AsaMatrix=224}] run function asa_animator:reus/anim/damage_stun/keyframes/224
execute if entity @s[scores={AsaMatrix=225}] run function asa_animator:reus/anim/damage_stun/keyframes/225
execute if entity @s[scores={AsaMatrix=226}] run function asa_animator:reus/anim/damage_stun/keyframes/226
execute if entity @s[scores={AsaMatrix=227}] run function asa_animator:reus/anim/damage_stun/keyframes/227
execute if entity @s[scores={AsaMatrix=228}] run function asa_animator:reus/anim/damage_stun/keyframes/228
execute if entity @s[scores={AsaMatrix=229}] run function asa_animator:reus/anim/damage_stun/keyframes/229
execute if entity @s[scores={AsaMatrix=230}] run function asa_animator:reus/anim/damage_stun/keyframes/230
execute if entity @s[scores={AsaMatrix=231}] run function asa_animator:reus/anim/damage_stun/keyframes/231
execute if entity @s[scores={AsaMatrix=232}] run function asa_animator:reus/anim/damage_stun/keyframes/232
execute if entity @s[scores={AsaMatrix=233}] run function asa_animator:reus/anim/damage_stun/keyframes/233
execute if entity @s[scores={AsaMatrix=234}] run function asa_animator:reus/anim/damage_stun/keyframes/234
execute if entity @s[scores={AsaMatrix=235}] run function asa_animator:reus/anim/damage_stun/keyframes/235
execute if entity @s[scores={AsaMatrix=236}] run function asa_animator:reus/anim/damage_stun/keyframes/236
execute if entity @s[scores={AsaMatrix=237}] run function asa_animator:reus/anim/damage_stun/keyframes/237
execute if entity @s[scores={AsaMatrix=238}] run function asa_animator:reus/anim/damage_stun/keyframes/238
execute if entity @s[scores={AsaMatrix=239..}] run function asa_animator:reus/anim/damage_stun/keyframes/239
execute if entity @s[scores={AsaMatrix=240..}] run function asa_animator:reus/anim/damage_stun/end
function asa_animator:reus/model
