# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0.00 ^0.00 ^0.00 ~8 ~
execute if entity @s[scores={AsaMatrix=9..20}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=21..25}] run tp @s ^0.05 ^-0.02 ^0.00 ~-3 ~
execute if entity @s[scores={AsaMatrix=26..30}] run tp @s ^0.05 ^0.62 ^0.00 ~-18 ~
execute if entity @s[scores={AsaMatrix=31..33}] run tp @s ^0.08 ^-0.63 ^0.00 ~-18 ~
execute if entity @s[scores={AsaMatrix=34..36}] run tp @s ^0.08 ^-0.50 ^0.00 ~-12 ~
execute if entity @s[scores={AsaMatrix=37..51}] run tp @s ^0.01 ^0.00 ^0.00 ~-3 ~
execute if entity @s[scores={AsaMatrix=52..66}] run tp @s ^-0.07 ^0.02 ^0.00 ~0.5 ~

# 移動
    execute if entity @s[scores={AsaMatrix=1}] at @s run function asa_animator:zinogre/anim/tail_whip_l/events/pos/set_pos
    execute if entity @s[scores={AsaMatrix=26..36}] run function asa_animator:zinogre/anim/tail_whip_l/events/pos/offset
    execute if entity @s[scores={AsaMatrix=52..66}] run function asa_animator:zinogre/manager/4_general/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 3 0.7
    execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:zinogre/manager/particle/step
    execute if entity @s[scores={AsaMatrix=36..38}] run function asa_animator:zinogre/manager/particle/step
    execute if entity @s[scores={AsaMatrix=28}] run playsound entity.player.attack.sweep master @a ~ ~ ~ 3 0.7
    execute if entity @s[scores={AsaMatrix=36}] run playsound entity.hoglin.step master @a ~ ~ ~ 3 0.7

# 攻撃
    execute if entity @s[tag=!DestroyTail,scores={AsaMatrix=26..33}] at @e[type=armor_stand,tag=ZinogreParts,tag=Tail3] run function asa_animator:zinogre/anim/tail_whip_l/events/damage
    execute if entity @s[tag=DestroyTail,scores={AsaMatrix=26..33}] at @e[type=armor_stand,tag=ZinogreParts,tag=Tail2] run function asa_animator:zinogre/anim/tail_whip_l/events/damage

# 状態更新
    execute if entity @s[scores={AsaMatrix=26}] run tag @s add IsFlying
    execute if entity @s[scores={AsaMatrix=36}] run tag @s remove IsFlying

# 高度調整
    execute if entity @s[scores={AsaMatrix=1..5}] at @s if block ~ ~-0.1 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=1..5}] at @s unless block ~ ~0.1 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=36..51}] at @s if block ~ ~0.2 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=36..51}] at @s unless block ~ ~0.4 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~ ~ ~
    execute if entity @s[scores={AsaMatrix=55..}] at @s if block ~ ~-0.1 ~ #asa_animator:no_collision run function asa_animator:general/check_ground
    execute if entity @s[scores={AsaMatrix=55..}] at @s unless block ~ ~0.1 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~ ~ ~

# 移行
    # execute if entity @s[tag=IsThunder,scores={AsaMatrix=37}] if predicate asa_animator:zinogre/combo run function asa_animator:zinogre/anim/tail_whip_l/events/change
    
# Keyframe Functions
function asa_animator:zinogre/get_data
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/59
execute if entity @s[scores={AsaMatrix=60}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/60
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/61
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/62
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/63
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/64
execute if entity @s[scores={AsaMatrix=65}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/65
execute if entity @s[scores={AsaMatrix=66..}] run function asa_animator:zinogre/anim/tail_whip_r/keyframes/66
function asa_animator:zinogre/model
execute if entity @s[scores={AsaMatrix=67..}] run function asa_animator:zinogre/anim/tail_whip_r/end
