# This function was generated by ArmorstandAnimator
# Main Functions
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=6..12}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=13..23}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=24..30}] run tp @s ^0.00 ^0.00 ^0.03
execute if entity @s[scores={AsaMatrix=31..37}] run tp @s ^0.00 ^0.00 ^0.11
execute if entity @s[scores={AsaMatrix=38..47}] run tp @s ^0.00 ^0.00 ^0.00
execute if entity @s[scores={AsaMatrix=48..60}] run tp @s ^0.00 ^0.00 ^-0.08

# 移動
    execute if entity @s[scores={AsaMatrix=1..12}] if entity @e[tag=ReusAttackTarget,distance=..6] at @s run tp @s ^ ^ ^-0.4
    execute if entity @s[scores={AsaMatrix=1..25}] unless entity @e[tag=ReusAttackTarget,distance=..2] run function asa_animator:reus/manager/4_general/rotate
    execute if entity @s[scores={AsaMatrix=23..37}] unless entity @e[tag=ReusAttackTarget,distance=..6] at @s run tp @s ^ ^ ^0.7

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=12}] run playsound item.firecharge.use master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=12..23}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..5] at @s positioned ^ ^0.65 ^0.3 run particle flame ~ ~ ~ 0.1 0.1 0.1 0.05 10
    execute if entity @s[scores={AsaMatrix=23..37}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..5] at @s positioned ^ ^0.65 ^0.3 run particle lava ~ ~ ~ 0.1 0.1 0.1 0.05 3

# 攻撃
    execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/bite_charge/events/damage

# 高度調整
    execute at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:general/check_ground
    execute at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

# Keyframe Functions
function asa_animator:reus/get_data
execute if entity @s[scores={AsaMatrix=..1}] run function asa_animator:reus/anim/bite_charge/keyframes/1
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:reus/anim/bite_charge/keyframes/2
execute if entity @s[scores={AsaMatrix=3}] run function asa_animator:reus/anim/bite_charge/keyframes/3
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:reus/anim/bite_charge/keyframes/4
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:reus/anim/bite_charge/keyframes/5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/bite_charge/keyframes/6
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:reus/anim/bite_charge/keyframes/7
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:reus/anim/bite_charge/keyframes/8
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/bite_charge/keyframes/9
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:reus/anim/bite_charge/keyframes/10
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/bite_charge/keyframes/11
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:reus/anim/bite_charge/keyframes/12
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/bite_charge/keyframes/13
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:reus/anim/bite_charge/keyframes/14
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:reus/anim/bite_charge/keyframes/15
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/bite_charge/keyframes/16
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/bite_charge/keyframes/17
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:reus/anim/bite_charge/keyframes/18
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/bite_charge/keyframes/19
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/bite_charge/keyframes/20
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reus/anim/bite_charge/keyframes/21
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:reus/anim/bite_charge/keyframes/22
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:reus/anim/bite_charge/keyframes/23
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/bite_charge/keyframes/24
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:reus/anim/bite_charge/keyframes/25
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/bite_charge/keyframes/26
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/bite_charge/keyframes/27
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/bite_charge/keyframes/28
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:reus/anim/bite_charge/keyframes/29
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/bite_charge/keyframes/30
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/bite_charge/keyframes/31
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:reus/anim/bite_charge/keyframes/32
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/bite_charge/keyframes/33
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:reus/anim/bite_charge/keyframes/34
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/bite_charge/keyframes/35
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/bite_charge/keyframes/36
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:reus/anim/bite_charge/keyframes/37
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:reus/anim/bite_charge/keyframes/38
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/bite_charge/keyframes/39
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:reus/anim/bite_charge/keyframes/40
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/bite_charge/keyframes/41
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:reus/anim/bite_charge/keyframes/42
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/bite_charge/keyframes/43
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:reus/anim/bite_charge/keyframes/44
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:reus/anim/bite_charge/keyframes/45
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/bite_charge/keyframes/46
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:reus/anim/bite_charge/keyframes/47
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:reus/anim/bite_charge/keyframes/48
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:reus/anim/bite_charge/keyframes/49
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:reus/anim/bite_charge/keyframes/50
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/bite_charge/keyframes/51
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:reus/anim/bite_charge/keyframes/52
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/bite_charge/keyframes/53
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/bite_charge/keyframes/54
execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:reus/anim/bite_charge/keyframes/55
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/bite_charge/keyframes/56
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:reus/anim/bite_charge/keyframes/57
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:reus/anim/bite_charge/keyframes/58
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/bite_charge/keyframes/59
execute if entity @s[scores={AsaMatrix=60..}] run function asa_animator:reus/anim/bite_charge/keyframes/60
execute if entity @s[scores={AsaMatrix=61..}] run function asa_animator:reus/anim/bite_charge/end
function asa_animator:reus/model
